<?php

declare(strict_types=1);

/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV3Lib\Tests;

use Core\Types\CallbackCatcher;
use SplititWebApiV3Lib\Authentication\OAuth2ProductionCredentialsBuilder;
use SplititWebApiV3Lib\Authentication\OAuth2SandboxCredentialsBuilder;
use SplititWebApiV3Lib\SplititWebApiV3Client;
use SplititWebApiV3Lib\SplititWebApiV3ClientBuilder;

class ClientFactory
{
    public static function create(CallbackCatcher $httpCallback): SplititWebApiV3Client
    {
        $clientBuilder = SplititWebApiV3ClientBuilder::init();
        $clientBuilder = self::addConfigurationFromEnvironment($clientBuilder);
        $clientBuilder = self::addTestConfiguration($clientBuilder);
        return $clientBuilder->httpCallback($httpCallback)->build();
    }

    public static function addTestConfiguration(SplititWebApiV3ClientBuilder $builder): SplititWebApiV3ClientBuilder
    {
        return $builder;
    }

    public static function addConfigurationFromEnvironment(
        SplititWebApiV3ClientBuilder $builder
    ): SplititWebApiV3ClientBuilder {
        $timeout = getenv('SPLITIT_WEB_API_V_3_LIB_TIMEOUT');
        $numberOfRetries = getenv('SPLITIT_WEB_API_V_3_LIB_NUMBER_OF_RETRIES');
        $maximumRetryWaitTime = getenv('SPLITIT_WEB_API_V_3_LIB_MAXIMUM_RETRY_WAIT_TIME');
        $environment = getenv('SPLITIT_WEB_API_V_3_LIB_ENVIRONMENT');
        $oAuthClientId = getenv('SPLITIT_WEB_API_V_3_LIB_O_AUTH_CLIENT_ID');
        $oAuthClientSecret = getenv('SPLITIT_WEB_API_V_3_LIB_O_AUTH_CLIENT_SECRET');
        $oAuthClientId2 = getenv('SPLITIT_WEB_API_V_3_LIB_O_AUTH_CLIENT_ID_2');
        $oAuthClientSecret2 = getenv('SPLITIT_WEB_API_V_3_LIB_O_AUTH_CLIENT_SECRET_2');

        if (!empty($timeout) && \is_numeric($timeout)) {
            $builder->timeout(intval($timeout));
        }

        if (!empty($numberOfRetries) && \is_numeric($numberOfRetries)) {
            $builder->numberOfRetries(intval($numberOfRetries));
        }

        if (!empty($maximumRetryWaitTime) && \is_numeric($maximumRetryWaitTime)) {
            $builder->maximumRetryWaitTime(intval($maximumRetryWaitTime));
        }

        if (!empty($environment)) {
            $builder->environment($environment);
        }

        if (!empty($oAuthClientId) && !empty($oAuthClientSecret)) {
            $builder->oAuth2SandboxCredentials(
                OAuth2SandboxCredentialsBuilder::init($oAuthClientId, $oAuthClientSecret)
            );
        }

        if (!empty($oAuthClientId2) && !empty($oAuthClientSecret2)) {
            $builder->oAuth2ProductionCredentials(
                OAuth2ProductionCredentialsBuilder::init($oAuthClientId2, $oAuthClientSecret2)
            );
        }

        return $builder;
    }
}
