<?php

declare(strict_types=1);

/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV3Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV3Lib\Models\AddressData;

/**
 * Builder for model AddressData
 *
 * @see AddressData
 */
class AddressDataBuilder
{
    /**
     * @var AddressData
     */
    private $instance;

    private function __construct(AddressData $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Address Data Builder object.
     */
    public static function init(): self
    {
        return new self(new AddressData());
    }

    /**
     * Sets Address Line field.
     *
     * @param string|null $value
     */
    public function addressLine(?string $value): self
    {
        $this->instance->setAddressLine($value);
        return $this;
    }

    /**
     * Sets Address Line 2 field.
     *
     * @param string|null $value
     */
    public function addressLine2(?string $value): self
    {
        $this->instance->setAddressLine2($value);
        return $this;
    }

    /**
     * Sets City field.
     *
     * @param string|null $value
     */
    public function city(?string $value): self
    {
        $this->instance->setCity($value);
        return $this;
    }

    /**
     * Sets Country field.
     *
     * @param string|null $value
     */
    public function country(?string $value): self
    {
        $this->instance->setCountry($value);
        return $this;
    }

    /**
     * Sets State field.
     *
     * @param string|null $value
     */
    public function state(?string $value): self
    {
        $this->instance->setState($value);
        return $this;
    }

    /**
     * Sets Zip field.
     *
     * @param string|null $value
     */
    public function zip(?string $value): self
    {
        $this->instance->setZip($value);
        return $this;
    }

    /**
     * Initializes a new Address Data object.
     */
    public function build(): AddressData
    {
        return CoreHelper::clone($this->instance);
    }
}
