<?php

declare(strict_types=1);

/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV3Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV3Lib\Models\CardData;

/**
 * Builder for model CardData
 *
 * @see CardData
 */
class CardDataBuilder
{
    /**
     * @var CardData
     */
    private $instance;

    private function __construct(CardData $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Card Data Builder object.
     */
    public static function init(): self
    {
        return new self(new CardData());
    }

    /**
     * Sets Card Holder Full Name field.
     *
     * @param string|null $value
     */
    public function cardHolderFullName(?string $value): self
    {
        $this->instance->setCardHolderFullName($value);
        return $this;
    }

    /**
     * Sets Card Number field.
     *
     * @param string|null $value
     */
    public function cardNumber(?string $value): self
    {
        $this->instance->setCardNumber($value);
        return $this;
    }

    /**
     * Sets Card Exp Year field.
     *
     * @param string|null $value
     */
    public function cardExpYear(?string $value): self
    {
        $this->instance->setCardExpYear($value);
        return $this;
    }

    /**
     * Sets Card Exp Month field.
     *
     * @param string|null $value
     */
    public function cardExpMonth(?string $value): self
    {
        $this->instance->setCardExpMonth($value);
        return $this;
    }

    /**
     * Sets Card Cvv field.
     *
     * @param string|null $value
     */
    public function cardCvv(?string $value): self
    {
        $this->instance->setCardCvv($value);
        return $this;
    }

    /**
     * Sets Card Brand field.
     *
     * @param string|null $value
     */
    public function cardBrand(?string $value): self
    {
        $this->instance->setCardBrand($value);
        return $this;
    }

    /**
     * Sets Card Type field.
     *
     * @param string|null $value
     */
    public function cardType(?string $value): self
    {
        $this->instance->setCardType($value);
        return $this;
    }

    /**
     * Initializes a new Card Data object.
     */
    public function build(): CardData
    {
        return CoreHelper::clone($this->instance);
    }
}
