<?php

declare(strict_types=1);

/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV3Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV3Lib\Models\AddressData;
use SplititWebApiV3Lib\Models\CardData;
use SplititWebApiV3Lib\Models\CheckInstallmentsEligibilityRequest;
use SplititWebApiV3Lib\Models\PlanData;

/**
 * Builder for model CheckInstallmentsEligibilityRequest
 *
 * @see CheckInstallmentsEligibilityRequest
 */
class CheckInstallmentsEligibilityRequestBuilder
{
    /**
     * @var CheckInstallmentsEligibilityRequest
     */
    private $instance;

    private function __construct(CheckInstallmentsEligibilityRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Check Installments Eligibility Request Builder object.
     */
    public static function init(): self
    {
        return new self(new CheckInstallmentsEligibilityRequest());
    }

    /**
     * Sets Plan Data field.
     *
     * @param PlanData|null $value
     */
    public function planData(?PlanData $value): self
    {
        $this->instance->setPlanData($value);
        return $this;
    }

    /**
     * Sets Card Details field.
     *
     * @param CardData|null $value
     */
    public function cardDetails(?CardData $value): self
    {
        $this->instance->setCardDetails($value);
        return $this;
    }

    /**
     * Sets Billing Address field.
     *
     * @param AddressData|null $value
     */
    public function billingAddress(?AddressData $value): self
    {
        $this->instance->setBillingAddress($value);
        return $this;
    }

    /**
     * Sets Shopper Identifier field.
     *
     * @param string|null $value
     */
    public function shopperIdentifier(?string $value): self
    {
        $this->instance->setShopperIdentifier($value);
        return $this;
    }

    /**
     * Initializes a new Check Installments Eligibility Request object.
     */
    public function build(): CheckInstallmentsEligibilityRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
