<?php

declare(strict_types=1);

/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV3Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV3Lib\Models\EligibilityTermsAndConditionResponse;

/**
 * Builder for model EligibilityTermsAndConditionResponse
 *
 * @see EligibilityTermsAndConditionResponse
 */
class EligibilityTermsAndConditionResponseBuilder
{
    /**
     * @var EligibilityTermsAndConditionResponse
     */
    private $instance;

    private function __construct(EligibilityTermsAndConditionResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Eligibility Terms And Condition Response Builder object.
     */
    public static function init(): self
    {
        return new self(new EligibilityTermsAndConditionResponse());
    }

    /**
     * Sets Terms And Conditions field.
     *
     * @param string|null $value
     */
    public function termsAndConditions(?string $value): self
    {
        $this->instance->setTermsAndConditions($value);
        return $this;
    }

    /**
     * Sets Privacy Policy field.
     *
     * @param string|null $value
     */
    public function privacyPolicy(?string $value): self
    {
        $this->instance->setPrivacyPolicy($value);
        return $this;
    }

    /**
     * Sets Provider field.
     *
     * @param string|null $value
     */
    public function provider(?string $value): self
    {
        $this->instance->setProvider($value);
        return $this;
    }

    /**
     * Initializes a new Eligibility Terms And Condition Response object.
     */
    public function build(): EligibilityTermsAndConditionResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
