<?php

declare(strict_types=1);

/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV3Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV3Lib\Models\ErrorExtended;

/**
 * Builder for model ErrorExtended
 *
 * @see ErrorExtended
 */
class ErrorExtendedBuilder
{
    /**
     * @var ErrorExtended
     */
    private $instance;

    private function __construct(ErrorExtended $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Error Extended Builder object.
     */
    public static function init(): self
    {
        return new self(new ErrorExtended());
    }

    /**
     * Sets Code field.
     *
     * @param string|null $value
     */
    public function code(?string $value): self
    {
        $this->instance->setCode($value);
        return $this;
    }

    /**
     * Sets Message field.
     *
     * @param string|null $value
     */
    public function message(?string $value): self
    {
        $this->instance->setMessage($value);
        return $this;
    }

    /**
     * Sets Additional Info field.
     *
     * @param string|null $value
     */
    public function additionalInfo(?string $value): self
    {
        $this->instance->setAdditionalInfo($value);
        return $this;
    }

    /**
     * Sets Extra Data field.
     *
     * @param array<string,string>|null $value
     */
    public function extraData(?array $value): self
    {
        $this->instance->setExtraData($value);
        return $this;
    }

    /**
     * Initializes a new Error Extended object.
     */
    public function build(): ErrorExtended
    {
        return CoreHelper::clone($this->instance);
    }
}
