<?php

declare(strict_types=1);

/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV3Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV3Lib\Models\GatewayTokenData;

/**
 * Builder for model GatewayTokenData
 *
 * @see GatewayTokenData
 */
class GatewayTokenDataBuilder
{
    /**
     * @var GatewayTokenData
     */
    private $instance;

    private function __construct(GatewayTokenData $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Gateway Token Data Builder object.
     */
    public static function init(): self
    {
        return new self(new GatewayTokenData());
    }

    /**
     * Sets Token field.
     *
     * @param string|null $value
     */
    public function token(?string $value): self
    {
        $this->instance->setToken($value);
        return $this;
    }

    /**
     * Sets Last 4 Digit field.
     *
     * @param string|null $value
     */
    public function last4Digit(?string $value): self
    {
        $this->instance->setLast4Digit($value);
        return $this;
    }

    /**
     * Initializes a new Gateway Token Data object.
     */
    public function build(): GatewayTokenData
    {
        return CoreHelper::clone($this->instance);
    }
}
