<?php

declare(strict_types=1);

/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV3Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV3Lib\Models\IdentifierContract;

/**
 * Builder for model IdentifierContract
 *
 * @see IdentifierContract
 */
class IdentifierContractBuilder
{
    /**
     * @var IdentifierContract
     */
    private $instance;

    private function __construct(IdentifierContract $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Identifier Contract Builder object.
     */
    public static function init(): self
    {
        return new self(new IdentifierContract());
    }

    /**
     * Sets Ref Order Number field.
     *
     * @param string|null $value
     */
    public function refOrderNumber(?string $value): self
    {
        $this->instance->setRefOrderNumber($value);
        return $this;
    }

    /**
     * Sets Installment Plan Number field.
     *
     * @param string|null $value
     */
    public function installmentPlanNumber(?string $value): self
    {
        $this->instance->setInstallmentPlanNumber($value);
        return $this;
    }

    /**
     * Sets Extended Params field.
     *
     * @param array<string,string>|null $value
     */
    public function extendedParams(?array $value): self
    {
        $this->instance->setExtendedParams($value);
        return $this;
    }

    /**
     * Initializes a new Identifier Contract object.
     */
    public function build(): IdentifierContract
    {
        return CoreHelper::clone($this->instance);
    }
}
