<?php

declare(strict_types=1);

/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV3Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV3Lib\Models\AddressData;
use SplititWebApiV3Lib\Models\InitiatePlanResponse;
use SplititWebApiV3Lib\Models\ShopperData;

/**
 * Builder for model InitiatePlanResponse
 *
 * @see InitiatePlanResponse
 */
class InitiatePlanResponseBuilder
{
    /**
     * @var InitiatePlanResponse
     */
    private $instance;

    private function __construct(InitiatePlanResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Initiate Plan Response Builder object.
     *
     * @param string $status
     */
    public static function init(string $status): self
    {
        return new self(new InitiatePlanResponse($status));
    }

    /**
     * Sets Installment Plan Number field.
     *
     * @param string|null $value
     */
    public function installmentPlanNumber(?string $value): self
    {
        $this->instance->setInstallmentPlanNumber($value);
        return $this;
    }

    /**
     * Sets Ref Order Number field.
     *
     * @param string|null $value
     */
    public function refOrderNumber(?string $value): self
    {
        $this->instance->setRefOrderNumber($value);
        return $this;
    }

    /**
     * Sets Purchase Method field.
     *
     * @param string|null $value
     */
    public function purchaseMethod(?string $value): self
    {
        $this->instance->setPurchaseMethod($value);
        return $this;
    }

    /**
     * Sets Currency field.
     *
     * @param string|null $value
     */
    public function currency(?string $value): self
    {
        $this->instance->setCurrency($value);
        return $this;
    }

    /**
     * Sets Amount field.
     *
     * @param float|null $value
     */
    public function amount(?float $value): self
    {
        $this->instance->setAmount($value);
        return $this;
    }

    /**
     * Sets Extended Params field.
     *
     * @param array<string,string>|null $value
     */
    public function extendedParams(?array $value): self
    {
        $this->instance->setExtendedParams($value);
        return $this;
    }

    /**
     * Sets Shopper field.
     *
     * @param ShopperData|null $value
     */
    public function shopper(?ShopperData $value): self
    {
        $this->instance->setShopper($value);
        return $this;
    }

    /**
     * Sets Billing Address field.
     *
     * @param AddressData|null $value
     */
    public function billingAddress(?AddressData $value): self
    {
        $this->instance->setBillingAddress($value);
        return $this;
    }

    /**
     * Sets Checkout Url field.
     *
     * @param string|null $value
     */
    public function checkoutUrl(?string $value): self
    {
        $this->instance->setCheckoutUrl($value);
        return $this;
    }

    /**
     * Sets Principal Amount field.
     *
     * @param float|null $value
     */
    public function principalAmount(?float $value): self
    {
        $this->instance->setPrincipalAmount($value);
        return $this;
    }

    /**
     * Initializes a new Initiate Plan Response object.
     */
    public function build(): InitiatePlanResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
