<?php

declare(strict_types=1);

/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV3Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV3Lib\Models\InitiateRedirectionEndpointsModel;

/**
 * Builder for model InitiateRedirectionEndpointsModel
 *
 * @see InitiateRedirectionEndpointsModel
 */
class InitiateRedirectionEndpointsModelBuilder
{
    /**
     * @var InitiateRedirectionEndpointsModel
     */
    private $instance;

    private function __construct(InitiateRedirectionEndpointsModel $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Initiate Redirection Endpoints Model Builder object.
     */
    public static function init(): self
    {
        return new self(new InitiateRedirectionEndpointsModel());
    }

    /**
     * Sets Succeeded field.
     *
     * @param string|null $value
     */
    public function succeeded(?string $value): self
    {
        $this->instance->setSucceeded($value);
        return $this;
    }

    /**
     * Sets Failed field.
     *
     * @param string|null $value
     */
    public function failed(?string $value): self
    {
        $this->instance->setFailed($value);
        return $this;
    }

    /**
     * Sets Cancel field.
     *
     * @param string|null $value
     */
    public function cancel(?string $value): self
    {
        $this->instance->setCancel($value);
        return $this;
    }

    /**
     * Initializes a new Initiate Redirection Endpoints Model object.
     */
    public function build(): InitiateRedirectionEndpointsModel
    {
        return CoreHelper::clone($this->instance);
    }
}
