<?php

declare(strict_types=1);

/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV3Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV3Lib\Models\IdentifierContract;
use SplititWebApiV3Lib\Models\InstallmentPlanUpdateRequestByIdentifier;

/**
 * Builder for model InstallmentPlanUpdateRequestByIdentifier
 *
 * @see InstallmentPlanUpdateRequestByIdentifier
 */
class InstallmentPlanUpdateRequestByIdentifierBuilder
{
    /**
     * @var InstallmentPlanUpdateRequestByIdentifier
     */
    private $instance;

    private function __construct(InstallmentPlanUpdateRequestByIdentifier $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Installment Plan Update Request By Identifier Builder object.
     */
    public static function init(): self
    {
        return new self(new InstallmentPlanUpdateRequestByIdentifier());
    }

    /**
     * Sets Ref Order Number field.
     *
     * @param string|null $value
     */
    public function refOrderNumber(?string $value): self
    {
        $this->instance->setRefOrderNumber($value);
        return $this;
    }

    /**
     * Sets Tracking Number field.
     *
     * @param string|null $value
     */
    public function trackingNumber(?string $value): self
    {
        $this->instance->setTrackingNumber($value);
        return $this;
    }

    /**
     * Sets Capture field.
     *
     * @param bool|null $value
     */
    public function capture(?bool $value): self
    {
        $this->instance->setCapture($value);
        return $this;
    }

    /**
     * Sets Shipping Status field.
     *
     * @param string|null $value
     */
    public function shippingStatus(?string $value): self
    {
        $this->instance->setShippingStatus($value);
        return $this;
    }

    /**
     * Sets New Amount field.
     *
     * @param float|null $value
     */
    public function newAmount(?float $value): self
    {
        $this->instance->setNewAmount($value);
        return $this;
    }

    /**
     * Sets Identifier field.
     *
     * @param IdentifierContract|null $value
     */
    public function identifier(?IdentifierContract $value): self
    {
        $this->instance->setIdentifier($value);
        return $this;
    }

    /**
     * Initializes a new Installment Plan Update Request By Identifier object.
     */
    public function build(): InstallmentPlanUpdateRequestByIdentifier
    {
        return CoreHelper::clone($this->instance);
    }
}
