<?php

declare(strict_types=1);

/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV3Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV3Lib\Models\AddressDataModel;
use SplititWebApiV3Lib\Models\EventsEndpointsModel;
use SplititWebApiV3Lib\Models\InitiateRedirectionEndpointsModel;
use SplititWebApiV3Lib\Models\InstallmentPlanInitiateRequest;
use SplititWebApiV3Lib\Models\PlanDataModel;
use SplititWebApiV3Lib\Models\ProcessingData;
use SplititWebApiV3Lib\Models\ShopperData;
use SplititWebApiV3Lib\Models\UxSettingsModel;

/**
 * Builder for model InstallmentPlanInitiateRequest
 *
 * @see InstallmentPlanInitiateRequest
 */
class InstallmentPlanInitiateRequestBuilder
{
    /**
     * @var InstallmentPlanInitiateRequest
     */
    private $instance;

    private function __construct(InstallmentPlanInitiateRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Installment Plan Initiate Request Builder object.
     */
    public static function init(): self
    {
        return new self(new InstallmentPlanInitiateRequest());
    }

    /**
     * Sets Auto Capture field.
     *
     * @param bool|null $value
     */
    public function autoCapture(?bool $value): self
    {
        $this->instance->setAutoCapture($value);
        return $this;
    }

    /**
     * Sets Attempt 3 d Secure field.
     *
     * @param bool|null $value
     */
    public function attempt3dSecure(?bool $value): self
    {
        $this->instance->setAttempt3dSecure($value);
        return $this;
    }

    /**
     * Sets Shopper field.
     *
     * @param ShopperData|null $value
     */
    public function shopper(?ShopperData $value): self
    {
        $this->instance->setShopper($value);
        return $this;
    }

    /**
     * Sets Plan Data field.
     *
     * @param PlanDataModel|null $value
     */
    public function planData(?PlanDataModel $value): self
    {
        $this->instance->setPlanData($value);
        return $this;
    }

    /**
     * Sets Billing Address field.
     *
     * @param AddressDataModel|null $value
     */
    public function billingAddress(?AddressDataModel $value): self
    {
        $this->instance->setBillingAddress($value);
        return $this;
    }

    /**
     * Sets Redirect Urls field.
     *
     * @param InitiateRedirectionEndpointsModel|null $value
     */
    public function redirectUrls(?InitiateRedirectionEndpointsModel $value): self
    {
        $this->instance->setRedirectUrls($value);
        return $this;
    }

    /**
     * Sets Ux Settings field.
     *
     * @param UxSettingsModel|null $value
     */
    public function uxSettings(?UxSettingsModel $value): self
    {
        $this->instance->setUxSettings($value);
        return $this;
    }

    /**
     * Sets Events Endpoints field.
     *
     * @param EventsEndpointsModel|null $value
     */
    public function eventsEndpoints(?EventsEndpointsModel $value): self
    {
        $this->instance->setEventsEndpoints($value);
        return $this;
    }

    /**
     * Sets Processing Data field.
     *
     * @param ProcessingData|null $value
     */
    public function processingData(?ProcessingData $value): self
    {
        $this->instance->setProcessingData($value);
        return $this;
    }

    /**
     * Initializes a new Installment Plan Initiate Request object.
     */
    public function build(): InstallmentPlanInitiateRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
