<?php

declare(strict_types=1);

/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV3Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV3Lib\Models\InstallmentPlanUpdateRequest;

/**
 * Builder for model InstallmentPlanUpdateRequest
 *
 * @see InstallmentPlanUpdateRequest
 */
class InstallmentPlanUpdateRequestBuilder
{
    /**
     * @var InstallmentPlanUpdateRequest
     */
    private $instance;

    private function __construct(InstallmentPlanUpdateRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Installment Plan Update Request Builder object.
     */
    public static function init(): self
    {
        return new self(new InstallmentPlanUpdateRequest());
    }

    /**
     * Sets Ref Order Number field.
     *
     * @param string|null $value
     */
    public function refOrderNumber(?string $value): self
    {
        $this->instance->setRefOrderNumber($value);
        return $this;
    }

    /**
     * Sets Tracking Number field.
     *
     * @param string|null $value
     */
    public function trackingNumber(?string $value): self
    {
        $this->instance->setTrackingNumber($value);
        return $this;
    }

    /**
     * Sets Capture field.
     *
     * @param bool|null $value
     */
    public function capture(?bool $value): self
    {
        $this->instance->setCapture($value);
        return $this;
    }

    /**
     * Sets Shipping Status field.
     *
     * @param string|null $value
     */
    public function shippingStatus(?string $value): self
    {
        $this->instance->setShippingStatus($value);
        return $this;
    }

    /**
     * Sets New Amount field.
     *
     * @param string|null $value
     */
    public function newAmount(?string $value): self
    {
        $this->instance->setNewAmount($value);
        return $this;
    }

    /**
     * Initializes a new Installment Plan Update Request object.
     */
    public function build(): InstallmentPlanUpdateRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
