<?php

declare(strict_types=1);

/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV3Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV3Lib\Models\Installment;

/**
 * Builder for model Installment
 *
 * @see Installment
 */
class InstallmentBuilder
{
    /**
     * @var Installment
     */
    private $instance;

    private function __construct(Installment $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Installment Builder object.
     *
     * @param int $installmentNumber
     * @param float $amount
     * @param string $status
     */
    public static function init(int $installmentNumber, float $amount, string $status): self
    {
        return new self(new Installment($installmentNumber, $amount, $status));
    }

    /**
     * Sets Process Date Time field.
     *
     * @param \DateTime|null $value
     */
    public function processDateTime(?\DateTime $value): self
    {
        $this->instance->setProcessDateTime($value);
        return $this;
    }

    /**
     * Initializes a new Installment object.
     */
    public function build(): Installment
    {
        return CoreHelper::clone($this->instance);
    }
}
