<?php

declare(strict_types=1);

/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV3Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV3Lib\Models\InstallmentPlanUpdateResponse;

/**
 * Builder for model InstallmentPlanUpdateResponse
 *
 * @see InstallmentPlanUpdateResponse
 */
class InstallmentPlanUpdateResponseBuilder
{
    /**
     * @var InstallmentPlanUpdateResponse
     */
    private $instance;

    private function __construct(InstallmentPlanUpdateResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Installment Plan Update Response Builder object.
     *
     * @param string $status
     * @param string $shippingStatus
     */
    public static function init(string $status, string $shippingStatus): self
    {
        return new self(new InstallmentPlanUpdateResponse($status, $shippingStatus));
    }

    /**
     * Sets Ref Order Number field.
     *
     * @param string|null $value
     */
    public function refOrderNumber(?string $value): self
    {
        $this->instance->setRefOrderNumber($value);
        return $this;
    }

    /**
     * Sets Installment Plan Number field.
     *
     * @param string|null $value
     */
    public function installmentPlanNumber(?string $value): self
    {
        $this->instance->setInstallmentPlanNumber($value);
        return $this;
    }

    /**
     * Sets New Amount field.
     *
     * @param float|null $value
     */
    public function newAmount(?float $value): self
    {
        $this->instance->setNewAmount($value);
        return $this;
    }

    /**
     * Initializes a new Installment Plan Update Response object.
     */
    public function build(): InstallmentPlanUpdateResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
