<?php

declare(strict_types=1);

/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV3Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV3Lib\Models\InstallmentPlanSearchResponse;
use SplititWebApiV3Lib\Models\SearchInstallmentPlanResponseItem;

/**
 * Builder for model InstallmentPlanSearchResponse
 *
 * @see InstallmentPlanSearchResponse
 */
class InstallmentPlanSearchResponseBuilder
{
    /**
     * @var InstallmentPlanSearchResponse
     */
    private $instance;

    private function __construct(InstallmentPlanSearchResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Installment Plan Search Response Builder object.
     */
    public static function init(): self
    {
        return new self(new InstallmentPlanSearchResponse());
    }

    /**
     * Sets Plan List field.
     *
     * @param SearchInstallmentPlanResponseItem[]|null $value
     */
    public function planList(?array $value): self
    {
        $this->instance->setPlanList($value);
        return $this;
    }

    /**
     * Initializes a new Installment Plan Search Response object.
     */
    public function build(): InstallmentPlanSearchResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
