<?php

declare(strict_types=1);

/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV3Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV3Lib\Models\InstallmentPlanRefundResponse;
use SplititWebApiV3Lib\Models\RefundSummary;

/**
 * Builder for model InstallmentPlanRefundResponse
 *
 * @see InstallmentPlanRefundResponse
 */
class InstallmentPlanRefundResponseBuilder
{
    /**
     * @var InstallmentPlanRefundResponse
     */
    private $instance;

    private function __construct(InstallmentPlanRefundResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Installment Plan Refund Response Builder object.
     */
    public static function init(): self
    {
        return new self(new InstallmentPlanRefundResponse());
    }

    /**
     * Sets Refund Id field.
     *
     * @param string|null $value
     */
    public function refundId(?string $value): self
    {
        $this->instance->setRefundId($value);
        return $this;
    }

    /**
     * Sets Installment Plan Number field.
     *
     * @param string|null $value
     */
    public function installmentPlanNumber(?string $value): self
    {
        $this->instance->setInstallmentPlanNumber($value);
        return $this;
    }

    /**
     * Sets Currency field.
     *
     * @param string|null $value
     */
    public function currency(?string $value): self
    {
        $this->instance->setCurrency($value);
        return $this;
    }

    /**
     * Sets Non Credit Refund Amount field.
     *
     * @param float|null $value
     */
    public function nonCreditRefundAmount(?float $value): self
    {
        $this->instance->setNonCreditRefundAmount($value);
        return $this;
    }

    /**
     * Sets Credit Refund Amount field.
     *
     * @param float|null $value
     */
    public function creditRefundAmount(?float $value): self
    {
        $this->instance->setCreditRefundAmount($value);
        return $this;
    }

    /**
     * Sets Summary field.
     *
     * @param RefundSummary|null $value
     */
    public function summary(?RefundSummary $value): self
    {
        $this->instance->setSummary($value);
        return $this;
    }

    /**
     * Sets Reference Id field.
     *
     * @param string|null $value
     */
    public function referenceId(?string $value): self
    {
        $this->instance->setReferenceId($value);
        return $this;
    }

    /**
     * Initializes a new Installment Plan Refund Response object.
     */
    public function build(): InstallmentPlanRefundResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
