<?php

declare(strict_types=1);

/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV3Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV3Lib\Models\AddressData;
use SplititWebApiV3Lib\Models\AuthorizationModel;
use SplititWebApiV3Lib\Models\Installment;
use SplititWebApiV3Lib\Models\InstallmentPlanGetResponse;
use SplititWebApiV3Lib\Models\LinksData;
use SplititWebApiV3Lib\Models\PaymentMethodModel;
use SplititWebApiV3Lib\Models\RefundModel;
use SplititWebApiV3Lib\Models\ShopperData;

/**
 * Builder for model InstallmentPlanGetResponse
 *
 * @see InstallmentPlanGetResponse
 */
class InstallmentPlanGetResponseBuilder
{
    /**
     * @var InstallmentPlanGetResponse
     */
    private $instance;

    private function __construct(InstallmentPlanGetResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Installment Plan Get Response Builder object.
     *
     * @param \DateTime $dateCreated
     * @param string $status
     */
    public static function init(\DateTime $dateCreated, string $status): self
    {
        return new self(new InstallmentPlanGetResponse($dateCreated, $status));
    }

    /**
     * Sets Installment Plan Number field.
     *
     * @param string|null $value
     */
    public function installmentPlanNumber(?string $value): self
    {
        $this->instance->setInstallmentPlanNumber($value);
        return $this;
    }

    /**
     * Sets Ref Order Number field.
     *
     * @param string|null $value
     */
    public function refOrderNumber(?string $value): self
    {
        $this->instance->setRefOrderNumber($value);
        return $this;
    }

    /**
     * Sets Purchase Method field.
     *
     * @param string|null $value
     */
    public function purchaseMethod(?string $value): self
    {
        $this->instance->setPurchaseMethod($value);
        return $this;
    }

    /**
     * Sets Currency field.
     *
     * @param string|null $value
     */
    public function currency(?string $value): self
    {
        $this->instance->setCurrency($value);
        return $this;
    }

    /**
     * Sets Original Amount field.
     *
     * @param float|null $value
     */
    public function originalAmount(?float $value): self
    {
        $this->instance->setOriginalAmount($value);
        return $this;
    }

    /**
     * Sets Amount field.
     *
     * @param float|null $value
     */
    public function amount(?float $value): self
    {
        $this->instance->setAmount($value);
        return $this;
    }

    /**
     * Sets Authorization field.
     *
     * @param AuthorizationModel|null $value
     */
    public function authorization(?AuthorizationModel $value): self
    {
        $this->instance->setAuthorization($value);
        return $this;
    }

    /**
     * Sets Shopper field.
     *
     * @param ShopperData|null $value
     */
    public function shopper(?ShopperData $value): self
    {
        $this->instance->setShopper($value);
        return $this;
    }

    /**
     * Sets Billing Address field.
     *
     * @param AddressData|null $value
     */
    public function billingAddress(?AddressData $value): self
    {
        $this->instance->setBillingAddress($value);
        return $this;
    }

    /**
     * Sets Payment Method field.
     *
     * @param PaymentMethodModel|null $value
     */
    public function paymentMethod(?PaymentMethodModel $value): self
    {
        $this->instance->setPaymentMethod($value);
        return $this;
    }

    /**
     * Sets Extended Params field.
     *
     * @param array<string,string>|null $value
     */
    public function extendedParams(?array $value): self
    {
        $this->instance->setExtendedParams($value);
        return $this;
    }

    /**
     * Sets Installments field.
     *
     * @param Installment[]|null $value
     */
    public function installments(?array $value): self
    {
        $this->instance->setInstallments($value);
        return $this;
    }

    /**
     * Sets Refunds field.
     *
     * @param RefundModel[]|null $value
     */
    public function refunds(?array $value): self
    {
        $this->instance->setRefunds($value);
        return $this;
    }

    /**
     * Sets Links field.
     *
     * @param LinksData|null $value
     */
    public function links(?LinksData $value): self
    {
        $this->instance->setLinks($value);
        return $this;
    }

    /**
     * Initializes a new Installment Plan Get Response object.
     */
    public function build(): InstallmentPlanGetResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
