<?php

declare(strict_types=1);

/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV3Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV3Lib\Models\InstallmentPlanRefundRequest;

/**
 * Builder for model InstallmentPlanRefundRequest
 *
 * @see InstallmentPlanRefundRequest
 */
class InstallmentPlanRefundRequestBuilder
{
    /**
     * @var InstallmentPlanRefundRequest
     */
    private $instance;

    private function __construct(InstallmentPlanRefundRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Installment Plan Refund Request Builder object.
     *
     * @param string $amount
     */
    public static function init(string $amount): self
    {
        return new self(new InstallmentPlanRefundRequest($amount));
    }

    /**
     * Sets Refund Strategy field.
     *
     * @param string|null $value
     */
    public function refundStrategy(?string $value): self
    {
        $this->instance->setRefundStrategy($value);
        return $this;
    }

    /**
     * Sets Reference Id field.
     *
     * @param string|null $value
     */
    public function referenceId(?string $value): self
    {
        $this->instance->setReferenceId($value);
        return $this;
    }

    /**
     * Initializes a new Installment Plan Refund Request object.
     */
    public function build(): InstallmentPlanRefundRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
