<?php

declare(strict_types=1);

/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV3Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV3Lib\Models\AddressDataModel;
use SplititWebApiV3Lib\Models\EventsEndpointsModel;
use SplititWebApiV3Lib\Models\InstallmentPlanCreateRequest;
use SplititWebApiV3Lib\Models\PaymentMethodModel;
use SplititWebApiV3Lib\Models\PlanDataModel;
use SplititWebApiV3Lib\Models\ProcessingData;
use SplititWebApiV3Lib\Models\RedirectionEndpointsModel;
use SplititWebApiV3Lib\Models\ShopperData;

/**
 * Builder for model InstallmentPlanCreateRequest
 *
 * @see InstallmentPlanCreateRequest
 */
class InstallmentPlanCreateRequestBuilder
{
    /**
     * @var InstallmentPlanCreateRequest
     */
    private $instance;

    private function __construct(InstallmentPlanCreateRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Installment Plan Create Request Builder object.
     *
     * @param bool $autoCapture
     * @param bool $termsAndConditionsAccepted
     */
    public static function init(bool $autoCapture, bool $termsAndConditionsAccepted): self
    {
        return new self(new InstallmentPlanCreateRequest($autoCapture, $termsAndConditionsAccepted));
    }

    /**
     * Sets Attempt 3 d Secure field.
     *
     * @param bool|null $value
     */
    public function attempt3dSecure(?bool $value): self
    {
        $this->instance->setAttempt3dSecure($value);
        return $this;
    }

    /**
     * Sets Shopper field.
     *
     * @param ShopperData|null $value
     */
    public function shopper(?ShopperData $value): self
    {
        $this->instance->setShopper($value);
        return $this;
    }

    /**
     * Sets Plan Data field.
     *
     * @param PlanDataModel|null $value
     */
    public function planData(?PlanDataModel $value): self
    {
        $this->instance->setPlanData($value);
        return $this;
    }

    /**
     * Sets Billing Address field.
     *
     * @param AddressDataModel|null $value
     */
    public function billingAddress(?AddressDataModel $value): self
    {
        $this->instance->setBillingAddress($value);
        return $this;
    }

    /**
     * Sets Payment Method field.
     *
     * @param PaymentMethodModel|null $value
     */
    public function paymentMethod(?PaymentMethodModel $value): self
    {
        $this->instance->setPaymentMethod($value);
        return $this;
    }

    /**
     * Sets Redirect Urls field.
     *
     * @param RedirectionEndpointsModel|null $value
     */
    public function redirectUrls(?RedirectionEndpointsModel $value): self
    {
        $this->instance->setRedirectUrls($value);
        return $this;
    }

    /**
     * Sets Processing Data field.
     *
     * @param ProcessingData|null $value
     */
    public function processingData(?ProcessingData $value): self
    {
        $this->instance->setProcessingData($value);
        return $this;
    }

    /**
     * Sets Events Endpoints field.
     *
     * @param EventsEndpointsModel|null $value
     */
    public function eventsEndpoints(?EventsEndpointsModel $value): self
    {
        $this->instance->setEventsEndpoints($value);
        return $this;
    }

    /**
     * Initializes a new Installment Plan Create Request object.
     */
    public function build(): InstallmentPlanCreateRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
