<?php

declare(strict_types=1);

/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV3Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV3Lib\Models\LinksData;

/**
 * Builder for model LinksData
 *
 * @see LinksData
 */
class LinksDataBuilder
{
    /**
     * @var LinksData
     */
    private $instance;

    private function __construct(LinksData $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Links Data Builder object.
     */
    public static function init(): self
    {
        return new self(new LinksData());
    }

    /**
     * Sets Checkout field.
     *
     * @param string|null $value
     */
    public function checkout(?string $value): self
    {
        $this->instance->setCheckout($value);
        return $this;
    }

    /**
     * Sets Learn More field.
     *
     * @param string|null $value
     */
    public function learnMore(?string $value): self
    {
        $this->instance->setLearnMore($value);
        return $this;
    }

    /**
     * Sets Terms Conditions field.
     *
     * @param string|null $value
     */
    public function termsConditions(?string $value): self
    {
        $this->instance->setTermsConditions($value);
        return $this;
    }

    /**
     * Sets Privacy Policy field.
     *
     * @param string|null $value
     */
    public function privacyPolicy(?string $value): self
    {
        $this->instance->setPrivacyPolicy($value);
        return $this;
    }

    /**
     * Initializes a new Links Data object.
     */
    public function build(): LinksData
    {
        return CoreHelper::clone($this->instance);
    }
}
