<?php

declare(strict_types=1);

/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV3Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV3Lib\Models\LinksModel;

/**
 * Builder for model LinksModel
 *
 * @see LinksModel
 */
class LinksModelBuilder
{
    /**
     * @var LinksModel
     */
    private $instance;

    private function __construct(LinksModel $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Links Model Builder object.
     */
    public static function init(): self
    {
        return new self(new LinksModel());
    }

    /**
     * Sets Privacy Policy Url field.
     *
     * @param string|null $value
     */
    public function privacyPolicyUrl(?string $value): self
    {
        $this->instance->setPrivacyPolicyUrl($value);
        return $this;
    }

    /**
     * Sets Terms And Conditions Url field.
     *
     * @param string|null $value
     */
    public function termsAndConditionsUrl(?string $value): self
    {
        $this->instance->setTermsAndConditionsUrl($value);
        return $this;
    }

    /**
     * Sets Learn More Url field.
     *
     * @param string|null $value
     */
    public function learnMoreUrl(?string $value): self
    {
        $this->instance->setLearnMoreUrl($value);
        return $this;
    }

    /**
     * Initializes a new Links Model object.
     */
    public function build(): LinksModel
    {
        return CoreHelper::clone($this->instance);
    }
}
