<?php

declare(strict_types=1);

/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV3Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV3Lib\Models\BluesnapVaultedShopperToken;
use SplititWebApiV3Lib\Models\CardData;
use SplititWebApiV3Lib\Models\MockerShopperToken;
use SplititWebApiV3Lib\Models\PaymentMethodModel;
use SplititWebApiV3Lib\Models\SpreedlyToken;

/**
 * Builder for model PaymentMethodModel
 *
 * @see PaymentMethodModel
 */
class PaymentMethodModelBuilder
{
    /**
     * @var PaymentMethodModel
     */
    private $instance;

    private function __construct(PaymentMethodModel $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Payment Method Model Builder object.
     *
     * @param string $type
     */
    public static function init(string $type): self
    {
        return new self(new PaymentMethodModel($type));
    }

    /**
     * Sets Card field.
     *
     * @param CardData|null $value
     */
    public function card(?CardData $value): self
    {
        $this->instance->setCard($value);
        return $this;
    }

    /**
     * Sets Token field.
     *
     * @param string|null $value
     */
    public function token(?string $value): self
    {
        $this->instance->setToken($value);
        return $this;
    }

    /**
     * Sets Bluesnap Vaulted Shopper Token field.
     *
     * @param BluesnapVaultedShopperToken|null $value
     */
    public function bluesnapVaultedShopperToken(?BluesnapVaultedShopperToken $value): self
    {
        $this->instance->setBluesnapVaultedShopperToken($value);
        return $this;
    }

    /**
     * Sets Mocker Shopper Token field.
     *
     * @param MockerShopperToken|null $value
     */
    public function mockerShopperToken(?MockerShopperToken $value): self
    {
        $this->instance->setMockerShopperToken($value);
        return $this;
    }

    /**
     * Sets Spreedly Token field.
     *
     * @param SpreedlyToken|null $value
     */
    public function spreedlyToken(?SpreedlyToken $value): self
    {
        $this->instance->setSpreedlyToken($value);
        return $this;
    }

    /**
     * Sets Card PAR field.
     *
     * @param string|null $value
     */
    public function cardPAR(?string $value): self
    {
        $this->instance->setCardPAR($value);
        return $this;
    }

    /**
     * Initializes a new Payment Method Model object.
     */
    public function build(): PaymentMethodModel
    {
        return CoreHelper::clone($this->instance);
    }
}
