<?php

declare(strict_types=1);

/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV3Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV3Lib\Models\LinksModel;
use SplititWebApiV3Lib\Models\PaymentPlanOptionModel;

/**
 * Builder for model PaymentPlanOptionModel
 *
 * @see PaymentPlanOptionModel
 */
class PaymentPlanOptionModelBuilder
{
    /**
     * @var PaymentPlanOptionModel
     */
    private $instance;

    private function __construct(PaymentPlanOptionModel $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Payment Plan Option Model Builder object.
     *
     * @param int $numberOfInstallments
     * @param float $firstInstallmentAmount
     * @param float $installmentAmount
     * @param float $lastInstallmentAmount
     */
    public static function init(
        int $numberOfInstallments,
        float $firstInstallmentAmount,
        float $installmentAmount,
        float $lastInstallmentAmount
    ): self {
        return new self(new PaymentPlanOptionModel(
            $numberOfInstallments,
            $firstInstallmentAmount,
            $installmentAmount,
            $lastInstallmentAmount
        ));
    }

    /**
     * Sets Links field.
     *
     * @param LinksModel|null $value
     */
    public function links(?LinksModel $value): self
    {
        $this->instance->setLinks($value);
        return $this;
    }

    /**
     * Sets Terms And Conditions Brief field.
     *
     * @param string|null $value
     */
    public function termsAndConditionsBrief(?string $value): self
    {
        $this->instance->setTermsAndConditionsBrief($value);
        return $this;
    }

    /**
     * Sets Installment Frequency field.
     *
     * @param string|null $value
     */
    public function installmentFrequency(?string $value): self
    {
        $this->instance->setInstallmentFrequency($value);
        return $this;
    }

    /**
     * Initializes a new Payment Plan Option Model object.
     */
    public function build(): PaymentPlanOptionModel
    {
        return CoreHelper::clone($this->instance);
    }
}
