<?php

declare(strict_types=1);

/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV3Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV3Lib\Models\PlanData;
use SplititWebApiV3Lib\Models\ProcessingData;

/**
 * Builder for model PlanData
 *
 * @see PlanData
 */
class PlanDataBuilder
{
    /**
     * @var PlanData
     */
    private $instance;

    private function __construct(PlanData $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Plan Data Builder object.
     *
     * @param string $totalAmount
     * @param int $numberOfInstallments
     * @param string $purchaseMethod
     */
    public static function init(string $totalAmount, int $numberOfInstallments, string $purchaseMethod): self
    {
        return new self(new PlanData($totalAmount, $numberOfInstallments, $purchaseMethod));
    }

    /**
     * Sets Terminal Id field.
     *
     * @param string|null $value
     */
    public function terminalId(?string $value): self
    {
        $this->instance->setTerminalId($value);
        return $this;
    }

    /**
     * Sets First Installment Amount field.
     *
     * @param float|null $value
     */
    public function firstInstallmentAmount(?float $value): self
    {
        $this->instance->setFirstInstallmentAmount($value);
        return $this;
    }

    /**
     * Sets Currency field.
     *
     * @param string|null $value
     */
    public function currency(?string $value): self
    {
        $this->instance->setCurrency($value);
        return $this;
    }

    /**
     * Sets Ref Order Number field.
     *
     * @param string|null $value
     */
    public function refOrderNumber(?string $value): self
    {
        $this->instance->setRefOrderNumber($value);
        return $this;
    }

    /**
     * Sets Allowed Installment Options field.
     *
     * @param int[]|null $value
     */
    public function allowedInstallmentOptions(?array $value): self
    {
        $this->instance->setAllowedInstallmentOptions($value);
        return $this;
    }

    /**
     * Sets Tags field.
     *
     * @param array<string,string>|null $value
     */
    public function tags(?array $value): self
    {
        $this->instance->setTags($value);
        return $this;
    }

    /**
     * Sets Processing Data field.
     *
     * @param ProcessingData|null $value
     */
    public function processingData(?ProcessingData $value): self
    {
        $this->instance->setProcessingData($value);
        return $this;
    }

    /**
     * Sets First Installment Date field.
     *
     * @param \DateTime|null $value
     */
    public function firstInstallmentDate(?\DateTime $value): self
    {
        $this->instance->setFirstInstallmentDate($value);
        return $this;
    }

    /**
     * Initializes a new Plan Data object.
     */
    public function build(): PlanData
    {
        return CoreHelper::clone($this->instance);
    }
}
