<?php

declare(strict_types=1);

/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV3Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV3Lib\Models\PlanDataModel;

/**
 * Builder for model PlanDataModel
 *
 * @see PlanDataModel
 */
class PlanDataModelBuilder
{
    /**
     * @var PlanDataModel
     */
    private $instance;

    private function __construct(PlanDataModel $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Plan Data Model Builder object.
     *
     * @param string $totalAmount
     * @param string $purchaseMethod
     */
    public static function init(string $totalAmount, string $purchaseMethod): self
    {
        return new self(new PlanDataModel($totalAmount, $purchaseMethod));
    }

    /**
     * Sets Currency field.
     *
     * @param string|null $value
     */
    public function currency(?string $value): self
    {
        $this->instance->setCurrency($value);
        return $this;
    }

    /**
     * Sets Number Of Installments field.
     *
     * @param int|null $value
     */
    public function numberOfInstallments(?int $value): self
    {
        $this->instance->setNumberOfInstallments($value);
        return $this;
    }

    /**
     * Unsets Number Of Installments field.
     */
    public function unsetNumberOfInstallments(): self
    {
        $this->instance->unsetNumberOfInstallments();
        return $this;
    }

    /**
     * Sets Terminal Id field.
     *
     * @param string|null $value
     */
    public function terminalId(?string $value): self
    {
        $this->instance->setTerminalId($value);
        return $this;
    }

    /**
     * Sets Ref Order Number field.
     *
     * @param string|null $value
     */
    public function refOrderNumber(?string $value): self
    {
        $this->instance->setRefOrderNumber($value);
        return $this;
    }

    /**
     * Sets Extended Params field.
     *
     * @param array<string,string>|null $value
     */
    public function extendedParams(?array $value): self
    {
        $this->instance->setExtendedParams($value);
        return $this;
    }

    /**
     * Sets First Installment Amount field.
     *
     * @param string|null $value
     */
    public function firstInstallmentAmount(?string $value): self
    {
        $this->instance->setFirstInstallmentAmount($value);
        return $this;
    }

    /**
     * Sets First Installment Date field.
     *
     * @param \DateTime|null $value
     */
    public function firstInstallmentDate(?\DateTime $value): self
    {
        $this->instance->setFirstInstallmentDate($value);
        return $this;
    }

    /**
     * Initializes a new Plan Data Model object.
     */
    public function build(): PlanDataModel
    {
        return CoreHelper::clone($this->instance);
    }
}
