<?php

declare(strict_types=1);

/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV3Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV3Lib\Models\RedirectionEndpointsModel;

/**
 * Builder for model RedirectionEndpointsModel
 *
 * @see RedirectionEndpointsModel
 */
class RedirectionEndpointsModelBuilder
{
    /**
     * @var RedirectionEndpointsModel
     */
    private $instance;

    private function __construct(RedirectionEndpointsModel $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Redirection Endpoints Model Builder object.
     */
    public static function init(): self
    {
        return new self(new RedirectionEndpointsModel());
    }

    /**
     * Sets Authorize Succeeded field.
     *
     * @param string|null $value
     */
    public function authorizeSucceeded(?string $value): self
    {
        $this->instance->setAuthorizeSucceeded($value);
        return $this;
    }

    /**
     * Sets Succeeded field.
     *
     * @param string|null $value
     */
    public function succeeded(?string $value): self
    {
        $this->instance->setSucceeded($value);
        return $this;
    }

    /**
     * Sets Authorize Failed field.
     *
     * @param string|null $value
     */
    public function authorizeFailed(?string $value): self
    {
        $this->instance->setAuthorizeFailed($value);
        return $this;
    }

    /**
     * Sets Failed field.
     *
     * @param string|null $value
     */
    public function failed(?string $value): self
    {
        $this->instance->setFailed($value);
        return $this;
    }

    /**
     * Initializes a new Redirection Endpoints Model object.
     */
    public function build(): RedirectionEndpointsModel
    {
        return CoreHelper::clone($this->instance);
    }
}
