<?php

declare(strict_types=1);

/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV3Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV3Lib\Models\RefundSummary;

/**
 * Builder for model RefundSummary
 *
 * @see RefundSummary
 */
class RefundSummaryBuilder
{
    /**
     * @var RefundSummary
     */
    private $instance;

    private function __construct(RefundSummary $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Refund Summary Builder object.
     */
    public static function init(): self
    {
        return new self(new RefundSummary());
    }

    /**
     * Sets Total Amount field.
     *
     * @param float|null $value
     */
    public function totalAmount(?float $value): self
    {
        $this->instance->setTotalAmount($value);
        return $this;
    }

    /**
     * Sets Failed Amount field.
     *
     * @param float|null $value
     */
    public function failedAmount(?float $value): self
    {
        $this->instance->setFailedAmount($value);
        return $this;
    }

    /**
     * Sets Succeeded Amount field.
     *
     * @param float|null $value
     */
    public function succeededAmount(?float $value): self
    {
        $this->instance->setSucceededAmount($value);
        return $this;
    }

    /**
     * Sets Pending Amount field.
     *
     * @param float|null $value
     */
    public function pendingAmount(?float $value): self
    {
        $this->instance->setPendingAmount($value);
        return $this;
    }

    /**
     * Initializes a new Refund Summary object.
     */
    public function build(): RefundSummary
    {
        return CoreHelper::clone($this->instance);
    }
}
