<?php

declare(strict_types=1);

/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV3Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV3Lib\Models\ShopperData;

/**
 * Builder for model ShopperData
 *
 * @see ShopperData
 */
class ShopperDataBuilder
{
    /**
     * @var ShopperData
     */
    private $instance;

    private function __construct(ShopperData $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Shopper Data Builder object.
     */
    public static function init(): self
    {
        return new self(new ShopperData());
    }

    /**
     * Sets Full Name field.
     *
     * @param string|null $value
     */
    public function fullName(?string $value): self
    {
        $this->instance->setFullName($value);
        return $this;
    }

    /**
     * Sets Email field.
     *
     * @param string|null $value
     */
    public function email(?string $value): self
    {
        $this->instance->setEmail($value);
        return $this;
    }

    /**
     * Sets Phone Number field.
     *
     * @param string|null $value
     */
    public function phoneNumber(?string $value): self
    {
        $this->instance->setPhoneNumber($value);
        return $this;
    }

    /**
     * Sets Culture field.
     *
     * @param string|null $value
     */
    public function culture(?string $value): self
    {
        $this->instance->setCulture($value);
        return $this;
    }

    /**
     * Sets External Id field.
     *
     * @param string|null $value
     */
    public function externalId(?string $value): self
    {
        $this->instance->setExternalId($value);
        return $this;
    }

    /**
     * Initializes a new Shopper Data object.
     */
    public function build(): ShopperData
    {
        return CoreHelper::clone($this->instance);
    }
}
