<?php

declare(strict_types=1);

/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV3Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV3Lib\Models\SpreedlyToken;

/**
 * Builder for model SpreedlyToken
 *
 * @see SpreedlyToken
 */
class SpreedlyTokenBuilder
{
    /**
     * @var SpreedlyToken
     */
    private $instance;

    private function __construct(SpreedlyToken $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Spreedly Token Builder object.
     */
    public static function init(): self
    {
        return new self(new SpreedlyToken());
    }

    /**
     * Sets Token field.
     *
     * @param string|null $value
     */
    public function token(?string $value): self
    {
        $this->instance->setToken($value);
        return $this;
    }

    /**
     * Sets Last 4 Digit field.
     *
     * @param string|null $value
     */
    public function last4Digit(?string $value): self
    {
        $this->instance->setLast4Digit($value);
        return $this;
    }

    /**
     * Initializes a new Spreedly Token object.
     */
    public function build(): SpreedlyToken
    {
        return CoreHelper::clone($this->instance);
    }
}
