<?php

declare(strict_types=1);

/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV3Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV3Lib\Models\ThreeDSData;

/**
 * Builder for model ThreeDSData
 *
 * @see ThreeDSData
 */
class ThreeDSDataBuilder
{
    /**
     * @var ThreeDSData
     */
    private $instance;

    private function __construct(ThreeDSData $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Three DS Data Builder object.
     */
    public static function init(): self
    {
        return new self(new ThreeDSData());
    }

    /**
     * Sets ECI field.
     *
     * @param string|null $value
     */
    public function eCI(?string $value): self
    {
        $this->instance->setECI($value);
        return $this;
    }

    /**
     * Sets CAVV field.
     *
     * @param string|null $value
     */
    public function cAVV(?string $value): self
    {
        $this->instance->setCAVV($value);
        return $this;
    }

    /**
     * Sets XID field.
     *
     * @param string|null $value
     */
    public function xID(?string $value): self
    {
        $this->instance->setXID($value);
        return $this;
    }

    /**
     * Sets Directory Server Txn Id field.
     *
     * @param string|null $value
     */
    public function directoryServerTxnId(?string $value): self
    {
        $this->instance->setDirectoryServerTxnId($value);
        return $this;
    }

    /**
     * Sets Three DS Version field.
     *
     * @param string|null $value
     */
    public function threeDSVersion(?string $value): self
    {
        $this->instance->setThreeDSVersion($value);
        return $this;
    }

    /**
     * Sets Transaction Id field.
     *
     * @param string|null $value
     */
    public function transactionId(?string $value): self
    {
        $this->instance->setTransactionId($value);
        return $this;
    }

    /**
     * Initializes a new Three DS Data object.
     */
    public function build(): ThreeDSData
    {
        return CoreHelper::clone($this->instance);
    }
}
