<?php

declare(strict_types=1);

/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV3Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV3Lib\Models\ThreeDsRedirectDataV3;

/**
 * Builder for model ThreeDsRedirectDataV3
 *
 * @see ThreeDsRedirectDataV3
 */
class ThreeDsRedirectDataV3Builder
{
    /**
     * @var ThreeDsRedirectDataV3
     */
    private $instance;

    private function __construct(ThreeDsRedirectDataV3 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Three Ds Redirect Data V3 Builder object.
     */
    public static function init(): self
    {
        return new self(new ThreeDsRedirectDataV3());
    }

    /**
     * Sets Url field.
     *
     * @param string|null $value
     */
    public function url(?string $value): self
    {
        $this->instance->setUrl($value);
        return $this;
    }

    /**
     * Sets Verb field.
     *
     * @param string|null $value
     */
    public function verb(?string $value): self
    {
        $this->instance->setVerb($value);
        return $this;
    }

    /**
     * Sets Params field.
     *
     * @param array<string,string>|null $value
     */
    public function params(?array $value): self
    {
        $this->instance->setParams($value);
        return $this;
    }

    /**
     * Sets Client Redirect Url field.
     *
     * @param string|null $value
     */
    public function clientRedirectUrl(?string $value): self
    {
        $this->instance->setClientRedirectUrl($value);
        return $this;
    }

    /**
     * Initializes a new Three Ds Redirect Data V3 object.
     */
    public function build(): ThreeDsRedirectDataV3
    {
        return CoreHelper::clone($this->instance);
    }
}
