<?php

declare(strict_types=1);

/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV3Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV3Lib\Models\UxSettingsModel;

/**
 * Builder for model UxSettingsModel
 *
 * @see UxSettingsModel
 */
class UxSettingsModelBuilder
{
    /**
     * @var UxSettingsModel
     */
    private $instance;

    private function __construct(UxSettingsModel $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Ux Settings Model Builder object.
     */
    public static function init(): self
    {
        return new self(new UxSettingsModel());
    }

    /**
     * Sets Displayed Installment Options field.
     *
     * @param int[]|null $value
     */
    public function displayedInstallmentOptions(?array $value): self
    {
        $this->instance->setDisplayedInstallmentOptions($value);
        return $this;
    }

    /**
     * Initializes a new Ux Settings Model object.
     */
    public function build(): UxSettingsModel
    {
        return CoreHelper::clone($this->instance);
    }
}
