<?php

declare(strict_types=1);

/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV3Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV3Lib\Models\AuthorizationModel;
use SplititWebApiV3Lib\Models\VerifyAuthorizationResponse;

/**
 * Builder for model VerifyAuthorizationResponse
 *
 * @see VerifyAuthorizationResponse
 */
class VerifyAuthorizationResponseBuilder
{
    /**
     * @var VerifyAuthorizationResponse
     */
    private $instance;

    private function __construct(VerifyAuthorizationResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Verify Authorization Response Builder object.
     *
     * @param bool $isAuthorized
     */
    public static function init(bool $isAuthorized): self
    {
        return new self(new VerifyAuthorizationResponse($isAuthorized));
    }

    /**
     * Sets Authorization Amount field.
     *
     * @param float|null $value
     */
    public function authorizationAmount(?float $value): self
    {
        $this->instance->setAuthorizationAmount($value);
        return $this;
    }

    /**
     * Sets Authorization field.
     *
     * @param AuthorizationModel|null $value
     */
    public function authorization(?AuthorizationModel $value): self
    {
        $this->instance->setAuthorization($value);
        return $this;
    }

    /**
     * Initializes a new Verify Authorization Response object.
     */
    public function build(): VerifyAuthorizationResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
