<?php

declare(strict_types=1);

/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV3Lib\Exceptions;

use SplititWebApiV3Lib\ApiHelper;

class FailedResponseException extends ApiException
{
    /**
     * @var string|null
     */
    private $traceId;

    /**
     * @var \SplititWebApiV3Lib\Models\ErrorExtended|null
     */
    private $error;

    /**
     * Returns Trace Id.
     */
    public function getTraceId(): ?string
    {
        return $this->traceId;
    }

    /**
     * Sets Trace Id.
     *
     * @maps TraceId
     */
    public function setTraceId(?string $traceId): void
    {
        $this->traceId = $traceId;
    }

    /**
     * Returns Error.
     */
    public function getError(): ?\SplititWebApiV3Lib\Models\ErrorExtended
    {
        return $this->error;
    }

    /**
     * Sets Error.
     *
     * @maps Error
     */
    public function setError(?\SplititWebApiV3Lib\Models\ErrorExtended $error): void
    {
        $this->error = $error;
    }

    /**
     * Converts the FailedResponseException object to a human-readable string representation.
     *
     * @return string The string representation of the FailedResponseException object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'FailedResponseException',
            ['traceId' => $this->traceId, 'error' => $this->error],
            parent::__toString()
        );
    }
}
