<?php

declare(strict_types=1);

/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV3Lib\Exceptions;

use SplititWebApiV3Lib\ApiHelper;

class PlanErrorResponseException extends ApiException
{
    /**
     * @var string|null
     */
    private $traceId;

    /**
     * @var \SplititWebApiV3Lib\Models\ErrorExtended|null
     */
    private $error;

    /**
     * @var string|null
     */
    private $installmentPlanNumber;

    /**
     * @var \SplititWebApiV3Lib\Models\PaymentInfo|null
     */
    private $paymentInfo;

    /**
     * Returns Trace Id.
     */
    public function getTraceId(): ?string
    {
        return $this->traceId;
    }

    /**
     * Sets Trace Id.
     *
     * @maps TraceId
     */
    public function setTraceId(?string $traceId): void
    {
        $this->traceId = $traceId;
    }

    /**
     * Returns Error.
     */
    public function getError(): ?\SplititWebApiV3Lib\Models\ErrorExtended
    {
        return $this->error;
    }

    /**
     * Sets Error.
     *
     * @maps Error
     */
    public function setError(?\SplititWebApiV3Lib\Models\ErrorExtended $error): void
    {
        $this->error = $error;
    }

    /**
     * Returns Installment Plan Number.
     */
    public function getInstallmentPlanNumber(): ?string
    {
        return $this->installmentPlanNumber;
    }

    /**
     * Sets Installment Plan Number.
     *
     * @maps InstallmentPlanNumber
     */
    public function setInstallmentPlanNumber(?string $installmentPlanNumber): void
    {
        $this->installmentPlanNumber = $installmentPlanNumber;
    }

    /**
     * Returns Payment Info.
     */
    public function getPaymentInfo(): ?\SplititWebApiV3Lib\Models\PaymentInfo
    {
        return $this->paymentInfo;
    }

    /**
     * Sets Payment Info.
     *
     * @maps PaymentInfo
     */
    public function setPaymentInfo(?\SplititWebApiV3Lib\Models\PaymentInfo $paymentInfo): void
    {
        $this->paymentInfo = $paymentInfo;
    }

    /**
     * Converts the PlanErrorResponseException object to a human-readable string representation.
     *
     * @return string The string representation of the PlanErrorResponseException object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'PlanErrorResponseException',
            [
                'traceId' => $this->traceId,
                'error' => $this->error,
                'installmentPlanNumber' => $this->installmentPlanNumber,
                'paymentInfo' => $this->paymentInfo
            ],
            parent::__toString()
        );
    }
}
