<?php

declare(strict_types=1);

/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV3Lib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

class CardBrandEnum
{
    public const MASTERCARD = 'Mastercard';

    public const VISA = 'Visa';

    public const AMERICANEXPRESS = 'AmericanExpress';

    public const MAESTRO = 'Maestro';

    public const JCB = 'JCB';

    public const CUP = 'CUP';

    public const UPI = 'UPI';

    public const DISCOVER = 'Discover';

    public const OTHER = 'Other';

    private const _ALL_VALUES = [
        self::MASTERCARD,
        self::VISA,
        self::AMERICANEXPRESS,
        self::MAESTRO,
        self::JCB,
        self::CUP,
        self::UPI,
        self::DISCOVER,
        self::OTHER
    ];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for CardBrandEnum.");
    }
}
