<?php

declare(strict_types=1);

/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV3Lib\Models;

use SplititWebApiV3Lib\ApiHelper;
use stdClass;

class CardData implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $cardHolderFullName;

    /**
     * @var string|null
     */
    private $cardNumber;

    /**
     * @var string|null
     */
    private $cardExpYear;

    /**
     * @var string|null
     */
    private $cardExpMonth;

    /**
     * @var string|null
     */
    private $cardCvv;

    /**
     * @var string|null
     */
    private $cardBrand;

    /**
     * @var string|null
     */
    private $cardType;

    /**
     * Returns Card Holder Full Name.
     */
    public function getCardHolderFullName(): ?string
    {
        return $this->cardHolderFullName;
    }

    /**
     * Sets Card Holder Full Name.
     *
     * @maps CardHolderFullName
     */
    public function setCardHolderFullName(?string $cardHolderFullName): void
    {
        $this->cardHolderFullName = $cardHolderFullName;
    }

    /**
     * Returns Card Number.
     */
    public function getCardNumber(): ?string
    {
        return $this->cardNumber;
    }

    /**
     * Sets Card Number.
     *
     * @maps CardNumber
     */
    public function setCardNumber(?string $cardNumber): void
    {
        $this->cardNumber = $cardNumber;
    }

    /**
     * Returns Card Exp Year.
     */
    public function getCardExpYear(): ?string
    {
        return $this->cardExpYear;
    }

    /**
     * Sets Card Exp Year.
     *
     * @maps CardExpYear
     */
    public function setCardExpYear(?string $cardExpYear): void
    {
        $this->cardExpYear = $cardExpYear;
    }

    /**
     * Returns Card Exp Month.
     */
    public function getCardExpMonth(): ?string
    {
        return $this->cardExpMonth;
    }

    /**
     * Sets Card Exp Month.
     *
     * @maps CardExpMonth
     */
    public function setCardExpMonth(?string $cardExpMonth): void
    {
        $this->cardExpMonth = $cardExpMonth;
    }

    /**
     * Returns Card Cvv.
     */
    public function getCardCvv(): ?string
    {
        return $this->cardCvv;
    }

    /**
     * Sets Card Cvv.
     *
     * @maps CardCvv
     */
    public function setCardCvv(?string $cardCvv): void
    {
        $this->cardCvv = $cardCvv;
    }

    /**
     * Returns Card Brand.
     */
    public function getCardBrand(): ?string
    {
        return $this->cardBrand;
    }

    /**
     * Sets Card Brand.
     *
     * @maps CardBrand
     * @factory \SplititWebApiV3Lib\Models\CardBrandEnum::checkValue
     */
    public function setCardBrand(?string $cardBrand): void
    {
        $this->cardBrand = $cardBrand;
    }

    /**
     * Returns Card Type.
     */
    public function getCardType(): ?string
    {
        return $this->cardType;
    }

    /**
     * Sets Card Type.
     *
     * @maps CardType
     * @factory \SplititWebApiV3Lib\Models\CardTypeEnum::checkValue
     */
    public function setCardType(?string $cardType): void
    {
        $this->cardType = $cardType;
    }

    /**
     * Converts the CardData object to a human-readable string representation.
     *
     * @return string The string representation of the CardData object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'CardData',
            [
                'cardHolderFullName' => $this->cardHolderFullName,
                'cardNumber' => $this->cardNumber,
                'cardExpYear' => $this->cardExpYear,
                'cardExpMonth' => $this->cardExpMonth,
                'cardCvv' => $this->cardCvv,
                'cardBrand' => $this->cardBrand,
                'cardType' => $this->cardType
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->cardHolderFullName)) {
            $json['CardHolderFullName'] = $this->cardHolderFullName;
        }
        if (isset($this->cardNumber)) {
            $json['CardNumber']         = $this->cardNumber;
        }
        if (isset($this->cardExpYear)) {
            $json['CardExpYear']        = $this->cardExpYear;
        }
        if (isset($this->cardExpMonth)) {
            $json['CardExpMonth']       = $this->cardExpMonth;
        }
        if (isset($this->cardCvv)) {
            $json['CardCvv']            = $this->cardCvv;
        }
        if (isset($this->cardBrand)) {
            $json['CardBrand']          = CardBrandEnum::checkValue($this->cardBrand);
        }
        if (isset($this->cardType)) {
            $json['CardType']           = CardTypeEnum::checkValue($this->cardType);
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
