<?php

declare(strict_types=1);

/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV3Lib\Models;

use SplititWebApiV3Lib\ApiHelper;
use stdClass;

class EligibilityTermsAndConditionResponse implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $termsAndConditions;

    /**
     * @var string|null
     */
    private $privacyPolicy;

    /**
     * @var string|null
     */
    private $provider;

    /**
     * Returns Terms and Conditions.
     */
    public function getTermsAndConditions(): ?string
    {
        return $this->termsAndConditions;
    }

    /**
     * Sets Terms and Conditions.
     *
     * @maps TermsAndConditions
     */
    public function setTermsAndConditions(?string $termsAndConditions): void
    {
        $this->termsAndConditions = $termsAndConditions;
    }

    /**
     * Returns Privacy Policy.
     */
    public function getPrivacyPolicy(): ?string
    {
        return $this->privacyPolicy;
    }

    /**
     * Sets Privacy Policy.
     *
     * @maps PrivacyPolicy
     */
    public function setPrivacyPolicy(?string $privacyPolicy): void
    {
        $this->privacyPolicy = $privacyPolicy;
    }

    /**
     * Returns Provider.
     */
    public function getProvider(): ?string
    {
        return $this->provider;
    }

    /**
     * Sets Provider.
     *
     * @maps Provider
     */
    public function setProvider(?string $provider): void
    {
        $this->provider = $provider;
    }

    /**
     * Converts the EligibilityTermsAndConditionResponse object to a human-readable string representation.
     *
     * @return string The string representation of the EligibilityTermsAndConditionResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'EligibilityTermsAndConditionResponse',
            [
                'termsAndConditions' => $this->termsAndConditions,
                'privacyPolicy' => $this->privacyPolicy,
                'provider' => $this->provider
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->termsAndConditions)) {
            $json['TermsAndConditions'] = $this->termsAndConditions;
        }
        if (isset($this->privacyPolicy)) {
            $json['PrivacyPolicy']      = $this->privacyPolicy;
        }
        if (isset($this->provider)) {
            $json['Provider']           = $this->provider;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
