<?php

declare(strict_types=1);

/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV3Lib\Models;

use SplititWebApiV3Lib\ApiHelper;
use stdClass;

class EventsEndpointsModel implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $createSucceeded;

    /**
     * Returns Create Succeeded.
     */
    public function getCreateSucceeded(): ?string
    {
        return $this->createSucceeded;
    }

    /**
     * Sets Create Succeeded.
     *
     * @maps CreateSucceeded
     */
    public function setCreateSucceeded(?string $createSucceeded): void
    {
        $this->createSucceeded = $createSucceeded;
    }

    /**
     * Converts the EventsEndpointsModel object to a human-readable string representation.
     *
     * @return string The string representation of the EventsEndpointsModel object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('EventsEndpointsModel', ['createSucceeded' => $this->createSucceeded]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->createSucceeded)) {
            $json['CreateSucceeded'] = $this->createSucceeded;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
