<?php

declare(strict_types=1);

/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV3Lib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

class GwAuthorizationStatusEnum
{
    public const NA = 'NA';

    public const SUCCEEDED = 'Succeeded';

    public const PENDING3DS = 'Pending3DS';

    public const FAILED = 'Failed';

    public const CANCELED = 'Canceled';

    public const VOIDED = 'Voided';

    private const _ALL_VALUES =
        [self::NA, self::SUCCEEDED, self::PENDING3DS, self::FAILED, self::CANCELED, self::VOIDED];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for GwAuthorizationStatusEnum.");
    }
}
