<?php

declare(strict_types=1);

/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV3Lib\Models;

use SplititWebApiV3Lib\ApiHelper;
use stdClass;

class IdentifierContract implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $refOrderNumber;

    /**
     * @var string|null
     */
    private $installmentPlanNumber;

    /**
     * @var array<string,string>|null
     */
    private $extendedParams;

    /**
     * Returns Ref Order Number.
     */
    public function getRefOrderNumber(): ?string
    {
        return $this->refOrderNumber;
    }

    /**
     * Sets Ref Order Number.
     *
     * @maps RefOrderNumber
     */
    public function setRefOrderNumber(?string $refOrderNumber): void
    {
        $this->refOrderNumber = $refOrderNumber;
    }

    /**
     * Returns Installment Plan Number.
     */
    public function getInstallmentPlanNumber(): ?string
    {
        return $this->installmentPlanNumber;
    }

    /**
     * Sets Installment Plan Number.
     *
     * @maps InstallmentPlanNumber
     */
    public function setInstallmentPlanNumber(?string $installmentPlanNumber): void
    {
        $this->installmentPlanNumber = $installmentPlanNumber;
    }

    /**
     * Returns Extended Params.
     *
     * @return array<string,string>|null
     */
    public function getExtendedParams(): ?array
    {
        return $this->extendedParams;
    }

    /**
     * Sets Extended Params.
     *
     * @maps ExtendedParams
     *
     * @param array<string,string>|null $extendedParams
     */
    public function setExtendedParams(?array $extendedParams): void
    {
        $this->extendedParams = $extendedParams;
    }

    /**
     * Converts the IdentifierContract object to a human-readable string representation.
     *
     * @return string The string representation of the IdentifierContract object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'IdentifierContract',
            [
                'refOrderNumber' => $this->refOrderNumber,
                'installmentPlanNumber' => $this->installmentPlanNumber,
                'extendedParams' => $this->extendedParams
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->refOrderNumber)) {
            $json['RefOrderNumber']        = $this->refOrderNumber;
        }
        if (isset($this->installmentPlanNumber)) {
            $json['InstallmentPlanNumber'] = $this->installmentPlanNumber;
        }
        if (isset($this->extendedParams)) {
            $json['ExtendedParams']        = $this->extendedParams;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
