<?php

declare(strict_types=1);

/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV3Lib\Models;

use SplititWebApiV3Lib\ApiHelper;
use stdClass;

class InitiateRedirectionEndpointsModel implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $succeeded;

    /**
     * @var string|null
     */
    private $failed;

    /**
     * @var string|null
     */
    private $cancel;

    /**
     * Returns Succeeded.
     */
    public function getSucceeded(): ?string
    {
        return $this->succeeded;
    }

    /**
     * Sets Succeeded.
     *
     * @maps Succeeded
     */
    public function setSucceeded(?string $succeeded): void
    {
        $this->succeeded = $succeeded;
    }

    /**
     * Returns Failed.
     */
    public function getFailed(): ?string
    {
        return $this->failed;
    }

    /**
     * Sets Failed.
     *
     * @maps Failed
     */
    public function setFailed(?string $failed): void
    {
        $this->failed = $failed;
    }

    /**
     * Returns Cancel.
     */
    public function getCancel(): ?string
    {
        return $this->cancel;
    }

    /**
     * Sets Cancel.
     *
     * @maps Cancel
     */
    public function setCancel(?string $cancel): void
    {
        $this->cancel = $cancel;
    }

    /**
     * Converts the InitiateRedirectionEndpointsModel object to a human-readable string representation.
     *
     * @return string The string representation of the InitiateRedirectionEndpointsModel object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'InitiateRedirectionEndpointsModel',
            ['succeeded' => $this->succeeded, 'failed' => $this->failed, 'cancel' => $this->cancel]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->succeeded)) {
            $json['Succeeded'] = $this->succeeded;
        }
        if (isset($this->failed)) {
            $json['Failed']    = $this->failed;
        }
        if (isset($this->cancel)) {
            $json['Cancel']    = $this->cancel;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
