<?php

declare(strict_types=1);

/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV3Lib\Models;

use SplititWebApiV3Lib\ApiHelper;
use stdClass;

class InstallmentPlanCreateRequest implements \JsonSerializable
{
    /**
     * @var bool
     */
    private $autoCapture;

    /**
     * @var bool|null
     */
    private $attempt3dSecure;

    /**
     * @var bool
     */
    private $termsAndConditionsAccepted;

    /**
     * @var ShopperData|null
     */
    private $shopper;

    /**
     * @var PlanDataModel|null
     */
    private $planData;

    /**
     * @var AddressDataModel|null
     */
    private $billingAddress;

    /**
     * @var PaymentMethodModel|null
     */
    private $paymentMethod;

    /**
     * @var RedirectionEndpointsModel|null
     */
    private $redirectUrls;

    /**
     * @var ProcessingData|null
     */
    private $processingData;

    /**
     * @var EventsEndpointsModel|null
     */
    private $eventsEndpoints;

    /**
     * @param bool $autoCapture
     * @param bool $termsAndConditionsAccepted
     */
    public function __construct(bool $autoCapture, bool $termsAndConditionsAccepted)
    {
        $this->autoCapture = $autoCapture;
        $this->termsAndConditionsAccepted = $termsAndConditionsAccepted;
    }

    /**
     * Returns Auto Capture.
     */
    public function getAutoCapture(): bool
    {
        return $this->autoCapture;
    }

    /**
     * Sets Auto Capture.
     *
     * @required
     * @maps AutoCapture
     */
    public function setAutoCapture(bool $autoCapture): void
    {
        $this->autoCapture = $autoCapture;
    }

    /**
     * Returns Attempt 3 D Secure.
     */
    public function getAttempt3dSecure(): ?bool
    {
        return $this->attempt3dSecure;
    }

    /**
     * Sets Attempt 3 D Secure.
     *
     * @maps Attempt3dSecure
     */
    public function setAttempt3dSecure(?bool $attempt3dSecure): void
    {
        $this->attempt3dSecure = $attempt3dSecure;
    }

    /**
     * Returns Terms and Conditions Accepted.
     */
    public function getTermsAndConditionsAccepted(): bool
    {
        return $this->termsAndConditionsAccepted;
    }

    /**
     * Sets Terms and Conditions Accepted.
     *
     * @required
     * @maps TermsAndConditionsAccepted
     */
    public function setTermsAndConditionsAccepted(bool $termsAndConditionsAccepted): void
    {
        $this->termsAndConditionsAccepted = $termsAndConditionsAccepted;
    }

    /**
     * Returns Shopper.
     */
    public function getShopper(): ?ShopperData
    {
        return $this->shopper;
    }

    /**
     * Sets Shopper.
     *
     * @maps Shopper
     */
    public function setShopper(?ShopperData $shopper): void
    {
        $this->shopper = $shopper;
    }

    /**
     * Returns Plan Data.
     */
    public function getPlanData(): ?PlanDataModel
    {
        return $this->planData;
    }

    /**
     * Sets Plan Data.
     *
     * @maps PlanData
     */
    public function setPlanData(?PlanDataModel $planData): void
    {
        $this->planData = $planData;
    }

    /**
     * Returns Billing Address.
     */
    public function getBillingAddress(): ?AddressDataModel
    {
        return $this->billingAddress;
    }

    /**
     * Sets Billing Address.
     *
     * @maps BillingAddress
     */
    public function setBillingAddress(?AddressDataModel $billingAddress): void
    {
        $this->billingAddress = $billingAddress;
    }

    /**
     * Returns Payment Method.
     */
    public function getPaymentMethod(): ?PaymentMethodModel
    {
        return $this->paymentMethod;
    }

    /**
     * Sets Payment Method.
     *
     * @maps PaymentMethod
     */
    public function setPaymentMethod(?PaymentMethodModel $paymentMethod): void
    {
        $this->paymentMethod = $paymentMethod;
    }

    /**
     * Returns Redirect Urls.
     */
    public function getRedirectUrls(): ?RedirectionEndpointsModel
    {
        return $this->redirectUrls;
    }

    /**
     * Sets Redirect Urls.
     *
     * @maps RedirectUrls
     */
    public function setRedirectUrls(?RedirectionEndpointsModel $redirectUrls): void
    {
        $this->redirectUrls = $redirectUrls;
    }

    /**
     * Returns Processing Data.
     */
    public function getProcessingData(): ?ProcessingData
    {
        return $this->processingData;
    }

    /**
     * Sets Processing Data.
     *
     * @maps ProcessingData
     */
    public function setProcessingData(?ProcessingData $processingData): void
    {
        $this->processingData = $processingData;
    }

    /**
     * Returns Events Endpoints.
     */
    public function getEventsEndpoints(): ?EventsEndpointsModel
    {
        return $this->eventsEndpoints;
    }

    /**
     * Sets Events Endpoints.
     *
     * @maps EventsEndpoints
     */
    public function setEventsEndpoints(?EventsEndpointsModel $eventsEndpoints): void
    {
        $this->eventsEndpoints = $eventsEndpoints;
    }

    /**
     * Converts the InstallmentPlanCreateRequest object to a human-readable string representation.
     *
     * @return string The string representation of the InstallmentPlanCreateRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'InstallmentPlanCreateRequest',
            [
                'autoCapture' => $this->autoCapture,
                'attempt3dSecure' => $this->attempt3dSecure,
                'termsAndConditionsAccepted' => $this->termsAndConditionsAccepted,
                'shopper' => $this->shopper,
                'planData' => $this->planData,
                'billingAddress' => $this->billingAddress,
                'paymentMethod' => $this->paymentMethod,
                'redirectUrls' => $this->redirectUrls,
                'processingData' => $this->processingData,
                'eventsEndpoints' => $this->eventsEndpoints
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['AutoCapture']                = $this->autoCapture;
        if (isset($this->attempt3dSecure)) {
            $json['Attempt3dSecure']        = $this->attempt3dSecure;
        }
        $json['TermsAndConditionsAccepted'] = $this->termsAndConditionsAccepted;
        if (isset($this->shopper)) {
            $json['Shopper']                = $this->shopper;
        }
        if (isset($this->planData)) {
            $json['PlanData']               = $this->planData;
        }
        if (isset($this->billingAddress)) {
            $json['BillingAddress']         = $this->billingAddress;
        }
        if (isset($this->paymentMethod)) {
            $json['PaymentMethod']          = $this->paymentMethod;
        }
        if (isset($this->redirectUrls)) {
            $json['RedirectUrls']           = $this->redirectUrls;
        }
        if (isset($this->processingData)) {
            $json['ProcessingData']         = $this->processingData;
        }
        if (isset($this->eventsEndpoints)) {
            $json['EventsEndpoints']        = $this->eventsEndpoints;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
