<?php

declare(strict_types=1);

/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV3Lib\Models;

use SplititWebApiV3Lib\ApiHelper;
use stdClass;

class InstallmentPlanRefundRequest implements \JsonSerializable
{
    /**
     * @var string
     */
    private $amount;

    /**
     * @var string|null
     */
    private $refundStrategy;

    /**
     * @var string|null
     */
    private $referenceId;

    /**
     * @param string $amount
     */
    public function __construct(string $amount)
    {
        $this->amount = $amount;
    }

    /**
     * Returns Amount.
     */
    public function getAmount(): string
    {
        return $this->amount;
    }

    /**
     * Sets Amount.
     *
     * @required
     * @maps Amount
     */
    public function setAmount(string $amount): void
    {
        $this->amount = $amount;
    }

    /**
     * Returns Refund Strategy.
     */
    public function getRefundStrategy(): ?string
    {
        return $this->refundStrategy;
    }

    /**
     * Sets Refund Strategy.
     *
     * @maps RefundStrategy
     * @factory \SplititWebApiV3Lib\Models\RefundStrategyEnum::checkValue
     */
    public function setRefundStrategy(?string $refundStrategy): void
    {
        $this->refundStrategy = $refundStrategy;
    }

    /**
     * Returns Reference Id.
     */
    public function getReferenceId(): ?string
    {
        return $this->referenceId;
    }

    /**
     * Sets Reference Id.
     *
     * @maps ReferenceId
     */
    public function setReferenceId(?string $referenceId): void
    {
        $this->referenceId = $referenceId;
    }

    /**
     * Converts the InstallmentPlanRefundRequest object to a human-readable string representation.
     *
     * @return string The string representation of the InstallmentPlanRefundRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'InstallmentPlanRefundRequest',
            [
                'amount' => $this->amount,
                'refundStrategy' => $this->refundStrategy,
                'referenceId' => $this->referenceId
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['Amount']             = $this->amount;
        if (isset($this->refundStrategy)) {
            $json['RefundStrategy'] = RefundStrategyEnum::checkValue($this->refundStrategy);
        }
        if (isset($this->referenceId)) {
            $json['ReferenceId']    = $this->referenceId;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
