<?php

declare(strict_types=1);

/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV3Lib\Models;

use SplititWebApiV3Lib\ApiHelper;
use stdClass;

class InstallmentPlanInitiateRequest implements \JsonSerializable
{
    /**
     * @var bool|null
     */
    private $autoCapture;

    /**
     * @var bool|null
     */
    private $attempt3dSecure;

    /**
     * @var ShopperData|null
     */
    private $shopper;

    /**
     * @var PlanDataModel|null
     */
    private $planData;

    /**
     * @var AddressDataModel|null
     */
    private $billingAddress;

    /**
     * @var InitiateRedirectionEndpointsModel|null
     */
    private $redirectUrls;

    /**
     * @var UxSettingsModel|null
     */
    private $uxSettings;

    /**
     * @var EventsEndpointsModel|null
     */
    private $eventsEndpoints;

    /**
     * @var ProcessingData|null
     */
    private $processingData;

    /**
     * Returns Auto Capture.
     */
    public function getAutoCapture(): ?bool
    {
        return $this->autoCapture;
    }

    /**
     * Sets Auto Capture.
     *
     * @maps AutoCapture
     */
    public function setAutoCapture(?bool $autoCapture): void
    {
        $this->autoCapture = $autoCapture;
    }

    /**
     * Returns Attempt 3 D Secure.
     */
    public function getAttempt3dSecure(): ?bool
    {
        return $this->attempt3dSecure;
    }

    /**
     * Sets Attempt 3 D Secure.
     *
     * @maps Attempt3dSecure
     */
    public function setAttempt3dSecure(?bool $attempt3dSecure): void
    {
        $this->attempt3dSecure = $attempt3dSecure;
    }

    /**
     * Returns Shopper.
     */
    public function getShopper(): ?ShopperData
    {
        return $this->shopper;
    }

    /**
     * Sets Shopper.
     *
     * @maps Shopper
     */
    public function setShopper(?ShopperData $shopper): void
    {
        $this->shopper = $shopper;
    }

    /**
     * Returns Plan Data.
     */
    public function getPlanData(): ?PlanDataModel
    {
        return $this->planData;
    }

    /**
     * Sets Plan Data.
     *
     * @maps PlanData
     */
    public function setPlanData(?PlanDataModel $planData): void
    {
        $this->planData = $planData;
    }

    /**
     * Returns Billing Address.
     */
    public function getBillingAddress(): ?AddressDataModel
    {
        return $this->billingAddress;
    }

    /**
     * Sets Billing Address.
     *
     * @maps BillingAddress
     */
    public function setBillingAddress(?AddressDataModel $billingAddress): void
    {
        $this->billingAddress = $billingAddress;
    }

    /**
     * Returns Redirect Urls.
     */
    public function getRedirectUrls(): ?InitiateRedirectionEndpointsModel
    {
        return $this->redirectUrls;
    }

    /**
     * Sets Redirect Urls.
     *
     * @maps RedirectUrls
     */
    public function setRedirectUrls(?InitiateRedirectionEndpointsModel $redirectUrls): void
    {
        $this->redirectUrls = $redirectUrls;
    }

    /**
     * Returns Ux Settings.
     */
    public function getUxSettings(): ?UxSettingsModel
    {
        return $this->uxSettings;
    }

    /**
     * Sets Ux Settings.
     *
     * @maps UxSettings
     */
    public function setUxSettings(?UxSettingsModel $uxSettings): void
    {
        $this->uxSettings = $uxSettings;
    }

    /**
     * Returns Events Endpoints.
     */
    public function getEventsEndpoints(): ?EventsEndpointsModel
    {
        return $this->eventsEndpoints;
    }

    /**
     * Sets Events Endpoints.
     *
     * @maps EventsEndpoints
     */
    public function setEventsEndpoints(?EventsEndpointsModel $eventsEndpoints): void
    {
        $this->eventsEndpoints = $eventsEndpoints;
    }

    /**
     * Returns Processing Data.
     */
    public function getProcessingData(): ?ProcessingData
    {
        return $this->processingData;
    }

    /**
     * Sets Processing Data.
     *
     * @maps ProcessingData
     */
    public function setProcessingData(?ProcessingData $processingData): void
    {
        $this->processingData = $processingData;
    }

    /**
     * Converts the InstallmentPlanInitiateRequest object to a human-readable string representation.
     *
     * @return string The string representation of the InstallmentPlanInitiateRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'InstallmentPlanInitiateRequest',
            [
                'autoCapture' => $this->autoCapture,
                'attempt3dSecure' => $this->attempt3dSecure,
                'shopper' => $this->shopper,
                'planData' => $this->planData,
                'billingAddress' => $this->billingAddress,
                'redirectUrls' => $this->redirectUrls,
                'uxSettings' => $this->uxSettings,
                'eventsEndpoints' => $this->eventsEndpoints,
                'processingData' => $this->processingData
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->autoCapture)) {
            $json['AutoCapture']     = $this->autoCapture;
        }
        if (isset($this->attempt3dSecure)) {
            $json['Attempt3dSecure'] = $this->attempt3dSecure;
        }
        if (isset($this->shopper)) {
            $json['Shopper']         = $this->shopper;
        }
        if (isset($this->planData)) {
            $json['PlanData']        = $this->planData;
        }
        if (isset($this->billingAddress)) {
            $json['BillingAddress']  = $this->billingAddress;
        }
        if (isset($this->redirectUrls)) {
            $json['RedirectUrls']    = $this->redirectUrls;
        }
        if (isset($this->uxSettings)) {
            $json['UxSettings']      = $this->uxSettings;
        }
        if (isset($this->eventsEndpoints)) {
            $json['EventsEndpoints'] = $this->eventsEndpoints;
        }
        if (isset($this->processingData)) {
            $json['ProcessingData']  = $this->processingData;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
