<?php

declare(strict_types=1);

/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV3Lib\Models;

use SplititWebApiV3Lib\ApiHelper;
use stdClass;

class InstallmentPlanUpdateRequestByIdentifier implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $refOrderNumber;

    /**
     * @var string|null
     */
    private $trackingNumber;

    /**
     * @var bool|null
     */
    private $capture;

    /**
     * @var string|null
     */
    private $shippingStatus;

    /**
     * @var float|null
     */
    private $newAmount;

    /**
     * @var IdentifierContract|null
     */
    private $identifier;

    /**
     * Returns Ref Order Number.
     */
    public function getRefOrderNumber(): ?string
    {
        return $this->refOrderNumber;
    }

    /**
     * Sets Ref Order Number.
     *
     * @maps RefOrderNumber
     */
    public function setRefOrderNumber(?string $refOrderNumber): void
    {
        $this->refOrderNumber = $refOrderNumber;
    }

    /**
     * Returns Tracking Number.
     */
    public function getTrackingNumber(): ?string
    {
        return $this->trackingNumber;
    }

    /**
     * Sets Tracking Number.
     *
     * @maps TrackingNumber
     */
    public function setTrackingNumber(?string $trackingNumber): void
    {
        $this->trackingNumber = $trackingNumber;
    }

    /**
     * Returns Capture.
     */
    public function getCapture(): ?bool
    {
        return $this->capture;
    }

    /**
     * Sets Capture.
     *
     * @maps Capture
     */
    public function setCapture(?bool $capture): void
    {
        $this->capture = $capture;
    }

    /**
     * Returns Shipping Status.
     */
    public function getShippingStatus(): ?string
    {
        return $this->shippingStatus;
    }

    /**
     * Sets Shipping Status.
     *
     * @maps ShippingStatus
     * @factory \SplititWebApiV3Lib\Models\ShippingStatusEnum::checkValue
     */
    public function setShippingStatus(?string $shippingStatus): void
    {
        $this->shippingStatus = $shippingStatus;
    }

    /**
     * Returns New Amount.
     */
    public function getNewAmount(): ?float
    {
        return $this->newAmount;
    }

    /**
     * Sets New Amount.
     *
     * @maps NewAmount
     */
    public function setNewAmount(?float $newAmount): void
    {
        $this->newAmount = $newAmount;
    }

    /**
     * Returns Identifier.
     */
    public function getIdentifier(): ?IdentifierContract
    {
        return $this->identifier;
    }

    /**
     * Sets Identifier.
     *
     * @maps Identifier
     */
    public function setIdentifier(?IdentifierContract $identifier): void
    {
        $this->identifier = $identifier;
    }

    /**
     * Converts the InstallmentPlanUpdateRequestByIdentifier object to a human-readable string
     * representation.
     *
     * @return string The string representation of the InstallmentPlanUpdateRequestByIdentifier object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'InstallmentPlanUpdateRequestByIdentifier',
            [
                'refOrderNumber' => $this->refOrderNumber,
                'trackingNumber' => $this->trackingNumber,
                'capture' => $this->capture,
                'shippingStatus' => $this->shippingStatus,
                'newAmount' => $this->newAmount,
                'identifier' => $this->identifier
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->refOrderNumber)) {
            $json['RefOrderNumber'] = $this->refOrderNumber;
        }
        if (isset($this->trackingNumber)) {
            $json['TrackingNumber'] = $this->trackingNumber;
        }
        if (isset($this->capture)) {
            $json['Capture']        = $this->capture;
        }
        if (isset($this->shippingStatus)) {
            $json['ShippingStatus'] = ShippingStatusEnum::checkValue($this->shippingStatus);
        }
        if (isset($this->newAmount)) {
            $json['NewAmount']      = $this->newAmount;
        }
        if (isset($this->identifier)) {
            $json['Identifier']     = $this->identifier;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
