<?php

declare(strict_types=1);

/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV3Lib\Models;

use SplititWebApiV3Lib\ApiHelper;
use stdClass;

class InstallmentPlanSearchResponse implements \JsonSerializable
{
    /**
     * @var SearchInstallmentPlanResponseItem[]|null
     */
    private $planList;

    /**
     * Returns Plan List.
     *
     * @return SearchInstallmentPlanResponseItem[]|null
     */
    public function getPlanList(): ?array
    {
        return $this->planList;
    }

    /**
     * Sets Plan List.
     *
     * @maps PlanList
     *
     * @param SearchInstallmentPlanResponseItem[]|null $planList
     */
    public function setPlanList(?array $planList): void
    {
        $this->planList = $planList;
    }

    /**
     * Converts the InstallmentPlanSearchResponse object to a human-readable string representation.
     *
     * @return string The string representation of the InstallmentPlanSearchResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('InstallmentPlanSearchResponse', ['planList' => $this->planList]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->planList)) {
            $json['PlanList'] = $this->planList;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
