<?php

declare(strict_types=1);

/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV3Lib\Models;

use SplititWebApiV3Lib\ApiHelper;
use stdClass;

class InstallmentPlanRefundResponse implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $refundId;

    /**
     * @var string|null
     */
    private $installmentPlanNumber;

    /**
     * @var string|null
     */
    private $currency;

    /**
     * @var float|null
     */
    private $nonCreditRefundAmount;

    /**
     * @var float|null
     */
    private $creditRefundAmount;

    /**
     * @var RefundSummary|null
     */
    private $summary;

    /**
     * @var string|null
     */
    private $referenceId;

    /**
     * Returns Refund Id.
     */
    public function getRefundId(): ?string
    {
        return $this->refundId;
    }

    /**
     * Sets Refund Id.
     *
     * @maps RefundId
     */
    public function setRefundId(?string $refundId): void
    {
        $this->refundId = $refundId;
    }

    /**
     * Returns Installment Plan Number.
     */
    public function getInstallmentPlanNumber(): ?string
    {
        return $this->installmentPlanNumber;
    }

    /**
     * Sets Installment Plan Number.
     *
     * @maps InstallmentPlanNumber
     */
    public function setInstallmentPlanNumber(?string $installmentPlanNumber): void
    {
        $this->installmentPlanNumber = $installmentPlanNumber;
    }

    /**
     * Returns Currency.
     */
    public function getCurrency(): ?string
    {
        return $this->currency;
    }

    /**
     * Sets Currency.
     *
     * @maps Currency
     */
    public function setCurrency(?string $currency): void
    {
        $this->currency = $currency;
    }

    /**
     * Returns Non Credit Refund Amount.
     */
    public function getNonCreditRefundAmount(): ?float
    {
        return $this->nonCreditRefundAmount;
    }

    /**
     * Sets Non Credit Refund Amount.
     *
     * @maps NonCreditRefundAmount
     */
    public function setNonCreditRefundAmount(?float $nonCreditRefundAmount): void
    {
        $this->nonCreditRefundAmount = $nonCreditRefundAmount;
    }

    /**
     * Returns Credit Refund Amount.
     */
    public function getCreditRefundAmount(): ?float
    {
        return $this->creditRefundAmount;
    }

    /**
     * Sets Credit Refund Amount.
     *
     * @maps CreditRefundAmount
     */
    public function setCreditRefundAmount(?float $creditRefundAmount): void
    {
        $this->creditRefundAmount = $creditRefundAmount;
    }

    /**
     * Returns Summary.
     */
    public function getSummary(): ?RefundSummary
    {
        return $this->summary;
    }

    /**
     * Sets Summary.
     *
     * @maps Summary
     */
    public function setSummary(?RefundSummary $summary): void
    {
        $this->summary = $summary;
    }

    /**
     * Returns Reference Id.
     */
    public function getReferenceId(): ?string
    {
        return $this->referenceId;
    }

    /**
     * Sets Reference Id.
     *
     * @maps ReferenceId
     */
    public function setReferenceId(?string $referenceId): void
    {
        $this->referenceId = $referenceId;
    }

    /**
     * Converts the InstallmentPlanRefundResponse object to a human-readable string representation.
     *
     * @return string The string representation of the InstallmentPlanRefundResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'InstallmentPlanRefundResponse',
            [
                'refundId' => $this->refundId,
                'installmentPlanNumber' => $this->installmentPlanNumber,
                'currency' => $this->currency,
                'nonCreditRefundAmount' => $this->nonCreditRefundAmount,
                'creditRefundAmount' => $this->creditRefundAmount,
                'summary' => $this->summary,
                'referenceId' => $this->referenceId
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->refundId)) {
            $json['RefundId']              = $this->refundId;
        }
        if (isset($this->installmentPlanNumber)) {
            $json['InstallmentPlanNumber'] = $this->installmentPlanNumber;
        }
        if (isset($this->currency)) {
            $json['Currency']              = $this->currency;
        }
        if (isset($this->nonCreditRefundAmount)) {
            $json['NonCreditRefundAmount'] = $this->nonCreditRefundAmount;
        }
        if (isset($this->creditRefundAmount)) {
            $json['CreditRefundAmount']    = $this->creditRefundAmount;
        }
        if (isset($this->summary)) {
            $json['Summary']               = $this->summary;
        }
        if (isset($this->referenceId)) {
            $json['ReferenceId']           = $this->referenceId;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
