<?php

declare(strict_types=1);

/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV3Lib\Models;

use SplititWebApiV3Lib\ApiHelper;
use stdClass;

class LinksData implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $checkout;

    /**
     * @var string|null
     */
    private $learnMore;

    /**
     * @var string|null
     */
    private $termsConditions;

    /**
     * @var string|null
     */
    private $privacyPolicy;

    /**
     * Returns Checkout.
     */
    public function getCheckout(): ?string
    {
        return $this->checkout;
    }

    /**
     * Sets Checkout.
     *
     * @maps Checkout
     */
    public function setCheckout(?string $checkout): void
    {
        $this->checkout = $checkout;
    }

    /**
     * Returns Learn More.
     */
    public function getLearnMore(): ?string
    {
        return $this->learnMore;
    }

    /**
     * Sets Learn More.
     *
     * @maps LearnMore
     */
    public function setLearnMore(?string $learnMore): void
    {
        $this->learnMore = $learnMore;
    }

    /**
     * Returns Terms Conditions.
     */
    public function getTermsConditions(): ?string
    {
        return $this->termsConditions;
    }

    /**
     * Sets Terms Conditions.
     *
     * @maps TermsConditions
     */
    public function setTermsConditions(?string $termsConditions): void
    {
        $this->termsConditions = $termsConditions;
    }

    /**
     * Returns Privacy Policy.
     */
    public function getPrivacyPolicy(): ?string
    {
        return $this->privacyPolicy;
    }

    /**
     * Sets Privacy Policy.
     *
     * @maps PrivacyPolicy
     */
    public function setPrivacyPolicy(?string $privacyPolicy): void
    {
        $this->privacyPolicy = $privacyPolicy;
    }

    /**
     * Converts the LinksData object to a human-readable string representation.
     *
     * @return string The string representation of the LinksData object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'LinksData',
            [
                'checkout' => $this->checkout,
                'learnMore' => $this->learnMore,
                'termsConditions' => $this->termsConditions,
                'privacyPolicy' => $this->privacyPolicy
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->checkout)) {
            $json['Checkout']        = $this->checkout;
        }
        if (isset($this->learnMore)) {
            $json['LearnMore']       = $this->learnMore;
        }
        if (isset($this->termsConditions)) {
            $json['TermsConditions'] = $this->termsConditions;
        }
        if (isset($this->privacyPolicy)) {
            $json['PrivacyPolicy']   = $this->privacyPolicy;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
