<?php

declare(strict_types=1);

/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV3Lib\Models;

use SplititWebApiV3Lib\ApiHelper;
use stdClass;

class LinksModel implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $privacyPolicyUrl;

    /**
     * @var string|null
     */
    private $termsAndConditionsUrl;

    /**
     * @var string|null
     */
    private $learnMoreUrl;

    /**
     * Returns Privacy Policy Url.
     */
    public function getPrivacyPolicyUrl(): ?string
    {
        return $this->privacyPolicyUrl;
    }

    /**
     * Sets Privacy Policy Url.
     *
     * @maps PrivacyPolicyUrl
     */
    public function setPrivacyPolicyUrl(?string $privacyPolicyUrl): void
    {
        $this->privacyPolicyUrl = $privacyPolicyUrl;
    }

    /**
     * Returns Terms and Conditions Url.
     */
    public function getTermsAndConditionsUrl(): ?string
    {
        return $this->termsAndConditionsUrl;
    }

    /**
     * Sets Terms and Conditions Url.
     *
     * @maps TermsAndConditionsUrl
     */
    public function setTermsAndConditionsUrl(?string $termsAndConditionsUrl): void
    {
        $this->termsAndConditionsUrl = $termsAndConditionsUrl;
    }

    /**
     * Returns Learn More Url.
     */
    public function getLearnMoreUrl(): ?string
    {
        return $this->learnMoreUrl;
    }

    /**
     * Sets Learn More Url.
     *
     * @maps LearnMoreUrl
     */
    public function setLearnMoreUrl(?string $learnMoreUrl): void
    {
        $this->learnMoreUrl = $learnMoreUrl;
    }

    /**
     * Converts the LinksModel object to a human-readable string representation.
     *
     * @return string The string representation of the LinksModel object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'LinksModel',
            [
                'privacyPolicyUrl' => $this->privacyPolicyUrl,
                'termsAndConditionsUrl' => $this->termsAndConditionsUrl,
                'learnMoreUrl' => $this->learnMoreUrl
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->privacyPolicyUrl)) {
            $json['PrivacyPolicyUrl']      = $this->privacyPolicyUrl;
        }
        if (isset($this->termsAndConditionsUrl)) {
            $json['TermsAndConditionsUrl'] = $this->termsAndConditionsUrl;
        }
        if (isset($this->learnMoreUrl)) {
            $json['LearnMoreUrl']          = $this->learnMoreUrl;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
