<?php

declare(strict_types=1);

/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV3Lib\Models;

use SplititWebApiV3Lib\ApiHelper;
use stdClass;

class PaymentPlanOptionModel implements \JsonSerializable
{
    /**
     * @var int
     */
    private $numberOfInstallments;

    /**
     * @var float
     */
    private $firstInstallmentAmount;

    /**
     * @var float
     */
    private $installmentAmount;

    /**
     * @var float
     */
    private $lastInstallmentAmount;

    /**
     * @var LinksModel|null
     */
    private $links;

    /**
     * @var string|null
     */
    private $termsAndConditionsBrief;

    /**
     * @var string|null
     */
    private $installmentFrequency;

    /**
     * @param int $numberOfInstallments
     * @param float $firstInstallmentAmount
     * @param float $installmentAmount
     * @param float $lastInstallmentAmount
     */
    public function __construct(
        int $numberOfInstallments,
        float $firstInstallmentAmount,
        float $installmentAmount,
        float $lastInstallmentAmount
    ) {
        $this->numberOfInstallments = $numberOfInstallments;
        $this->firstInstallmentAmount = $firstInstallmentAmount;
        $this->installmentAmount = $installmentAmount;
        $this->lastInstallmentAmount = $lastInstallmentAmount;
    }

    /**
     * Returns Number of Installments.
     */
    public function getNumberOfInstallments(): int
    {
        return $this->numberOfInstallments;
    }

    /**
     * Sets Number of Installments.
     *
     * @required
     * @maps NumberOfInstallments
     */
    public function setNumberOfInstallments(int $numberOfInstallments): void
    {
        $this->numberOfInstallments = $numberOfInstallments;
    }

    /**
     * Returns First Installment Amount.
     */
    public function getFirstInstallmentAmount(): float
    {
        return $this->firstInstallmentAmount;
    }

    /**
     * Sets First Installment Amount.
     *
     * @required
     * @maps FirstInstallmentAmount
     */
    public function setFirstInstallmentAmount(float $firstInstallmentAmount): void
    {
        $this->firstInstallmentAmount = $firstInstallmentAmount;
    }

    /**
     * Returns Installment Amount.
     */
    public function getInstallmentAmount(): float
    {
        return $this->installmentAmount;
    }

    /**
     * Sets Installment Amount.
     *
     * @required
     * @maps InstallmentAmount
     */
    public function setInstallmentAmount(float $installmentAmount): void
    {
        $this->installmentAmount = $installmentAmount;
    }

    /**
     * Returns Last Installment Amount.
     */
    public function getLastInstallmentAmount(): float
    {
        return $this->lastInstallmentAmount;
    }

    /**
     * Sets Last Installment Amount.
     *
     * @required
     * @maps LastInstallmentAmount
     */
    public function setLastInstallmentAmount(float $lastInstallmentAmount): void
    {
        $this->lastInstallmentAmount = $lastInstallmentAmount;
    }

    /**
     * Returns Links.
     */
    public function getLinks(): ?LinksModel
    {
        return $this->links;
    }

    /**
     * Sets Links.
     *
     * @maps Links
     */
    public function setLinks(?LinksModel $links): void
    {
        $this->links = $links;
    }

    /**
     * Returns Terms and Conditions Brief.
     */
    public function getTermsAndConditionsBrief(): ?string
    {
        return $this->termsAndConditionsBrief;
    }

    /**
     * Sets Terms and Conditions Brief.
     *
     * @maps TermsAndConditionsBrief
     */
    public function setTermsAndConditionsBrief(?string $termsAndConditionsBrief): void
    {
        $this->termsAndConditionsBrief = $termsAndConditionsBrief;
    }

    /**
     * Returns Installment Frequency.
     */
    public function getInstallmentFrequency(): ?string
    {
        return $this->installmentFrequency;
    }

    /**
     * Sets Installment Frequency.
     *
     * @maps InstallmentFrequency
     */
    public function setInstallmentFrequency(?string $installmentFrequency): void
    {
        $this->installmentFrequency = $installmentFrequency;
    }

    /**
     * Converts the PaymentPlanOptionModel object to a human-readable string representation.
     *
     * @return string The string representation of the PaymentPlanOptionModel object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'PaymentPlanOptionModel',
            [
                'numberOfInstallments' => $this->numberOfInstallments,
                'firstInstallmentAmount' => $this->firstInstallmentAmount,
                'installmentAmount' => $this->installmentAmount,
                'lastInstallmentAmount' => $this->lastInstallmentAmount,
                'links' => $this->links,
                'termsAndConditionsBrief' => $this->termsAndConditionsBrief,
                'installmentFrequency' => $this->installmentFrequency
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['NumberOfInstallments']        = $this->numberOfInstallments;
        $json['FirstInstallmentAmount']      = $this->firstInstallmentAmount;
        $json['InstallmentAmount']           = $this->installmentAmount;
        $json['LastInstallmentAmount']       = $this->lastInstallmentAmount;
        if (isset($this->links)) {
            $json['Links']                   = $this->links;
        }
        if (isset($this->termsAndConditionsBrief)) {
            $json['TermsAndConditionsBrief'] = $this->termsAndConditionsBrief;
        }
        if (isset($this->installmentFrequency)) {
            $json['InstallmentFrequency']    = $this->installmentFrequency;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
