<?php

declare(strict_types=1);

/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV3Lib\Models;

use SplititWebApiV3Lib\ApiHelper;
use SplititWebApiV3Lib\Utils\DateTimeHelper;
use stdClass;

class PlanDataModel implements \JsonSerializable
{
    /**
     * @var string
     */
    private $totalAmount;

    /**
     * @var string|null
     */
    private $currency;

    /**
     * @var array
     */
    private $numberOfInstallments = [];

    /**
     * @var string|null
     */
    private $terminalId;

    /**
     * @var string
     */
    private $purchaseMethod;

    /**
     * @var string|null
     */
    private $refOrderNumber;

    /**
     * @var array<string,string>|null
     */
    private $extendedParams;

    /**
     * @var string|null
     */
    private $firstInstallmentAmount;

    /**
     * @var \DateTime|null
     */
    private $firstInstallmentDate;

    /**
     * @param string $totalAmount
     * @param string $purchaseMethod
     */
    public function __construct(string $totalAmount, string $purchaseMethod)
    {
        $this->totalAmount = $totalAmount;
        $this->purchaseMethod = $purchaseMethod;
    }

    /**
     * Returns Total Amount.
     */
    public function getTotalAmount(): string
    {
        return $this->totalAmount;
    }

    /**
     * Sets Total Amount.
     *
     * @required
     * @maps TotalAmount
     */
    public function setTotalAmount(string $totalAmount): void
    {
        $this->totalAmount = $totalAmount;
    }

    /**
     * Returns Currency.
     */
    public function getCurrency(): ?string
    {
        return $this->currency;
    }

    /**
     * Sets Currency.
     *
     * @maps Currency
     */
    public function setCurrency(?string $currency): void
    {
        $this->currency = $currency;
    }

    /**
     * Returns Number of Installments.
     */
    public function getNumberOfInstallments(): ?int
    {
        if (count($this->numberOfInstallments) == 0) {
            return null;
        }
        return $this->numberOfInstallments['value'];
    }

    /**
     * Sets Number of Installments.
     *
     * @maps NumberOfInstallments
     */
    public function setNumberOfInstallments(?int $numberOfInstallments): void
    {
        $this->numberOfInstallments['value'] = $numberOfInstallments;
    }

    /**
     * Unsets Number of Installments.
     */
    public function unsetNumberOfInstallments(): void
    {
        $this->numberOfInstallments = [];
    }

    /**
     * Returns Terminal Id.
     */
    public function getTerminalId(): ?string
    {
        return $this->terminalId;
    }

    /**
     * Sets Terminal Id.
     *
     * @maps TerminalId
     */
    public function setTerminalId(?string $terminalId): void
    {
        $this->terminalId = $terminalId;
    }

    /**
     * Returns Purchase Method.
     */
    public function getPurchaseMethod(): string
    {
        return $this->purchaseMethod;
    }

    /**
     * Sets Purchase Method.
     *
     * @required
     * @maps PurchaseMethod
     * @factory \SplititWebApiV3Lib\Models\PurchaseMethodEnum::checkValue
     */
    public function setPurchaseMethod(string $purchaseMethod): void
    {
        $this->purchaseMethod = $purchaseMethod;
    }

    /**
     * Returns Ref Order Number.
     */
    public function getRefOrderNumber(): ?string
    {
        return $this->refOrderNumber;
    }

    /**
     * Sets Ref Order Number.
     *
     * @maps RefOrderNumber
     */
    public function setRefOrderNumber(?string $refOrderNumber): void
    {
        $this->refOrderNumber = $refOrderNumber;
    }

    /**
     * Returns Extended Params.
     *
     * @return array<string,string>|null
     */
    public function getExtendedParams(): ?array
    {
        return $this->extendedParams;
    }

    /**
     * Sets Extended Params.
     *
     * @maps ExtendedParams
     *
     * @param array<string,string>|null $extendedParams
     */
    public function setExtendedParams(?array $extendedParams): void
    {
        $this->extendedParams = $extendedParams;
    }

    /**
     * Returns First Installment Amount.
     */
    public function getFirstInstallmentAmount(): ?string
    {
        return $this->firstInstallmentAmount;
    }

    /**
     * Sets First Installment Amount.
     *
     * @maps FirstInstallmentAmount
     */
    public function setFirstInstallmentAmount(?string $firstInstallmentAmount): void
    {
        $this->firstInstallmentAmount = $firstInstallmentAmount;
    }

    /**
     * Returns First Installment Date.
     */
    public function getFirstInstallmentDate(): ?\DateTime
    {
        return $this->firstInstallmentDate;
    }

    /**
     * Sets First Installment Date.
     *
     * @maps FirstInstallmentDate
     * @factory \SplititWebApiV3Lib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setFirstInstallmentDate(?\DateTime $firstInstallmentDate): void
    {
        $this->firstInstallmentDate = $firstInstallmentDate;
    }

    /**
     * Converts the PlanDataModel object to a human-readable string representation.
     *
     * @return string The string representation of the PlanDataModel object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'PlanDataModel',
            [
                'totalAmount' => $this->totalAmount,
                'currency' => $this->currency,
                'numberOfInstallments' => $this->getNumberOfInstallments(),
                'terminalId' => $this->terminalId,
                'purchaseMethod' => $this->purchaseMethod,
                'refOrderNumber' => $this->refOrderNumber,
                'extendedParams' => $this->extendedParams,
                'firstInstallmentAmount' => $this->firstInstallmentAmount,
                'firstInstallmentDate' => $this->firstInstallmentDate
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['TotalAmount']                = $this->totalAmount;
        if (isset($this->currency)) {
            $json['Currency']               = $this->currency;
        }
        if (!empty($this->numberOfInstallments)) {
            $json['NumberOfInstallments']   = $this->numberOfInstallments['value'];
        }
        if (isset($this->terminalId)) {
            $json['TerminalId']             = $this->terminalId;
        }
        $json['PurchaseMethod']             = PurchaseMethodEnum::checkValue($this->purchaseMethod);
        if (isset($this->refOrderNumber)) {
            $json['RefOrderNumber']         = $this->refOrderNumber;
        }
        if (isset($this->extendedParams)) {
            $json['ExtendedParams']         = $this->extendedParams;
        }
        if (isset($this->firstInstallmentAmount)) {
            $json['FirstInstallmentAmount'] = $this->firstInstallmentAmount;
        }
        if (isset($this->firstInstallmentDate)) {
            $json['FirstInstallmentDate']   = DateTimeHelper::toRfc3339DateTime($this->firstInstallmentDate);
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
