<?php

declare(strict_types=1);

/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV3Lib\Models;

use SplititWebApiV3Lib\ApiHelper;
use stdClass;

class RedirectionEndpointsModel implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $authorizeSucceeded;

    /**
     * @var string|null
     */
    private $succeeded;

    /**
     * @var string|null
     */
    private $authorizeFailed;

    /**
     * @var string|null
     */
    private $failed;

    /**
     * Returns Authorize Succeeded.
     */
    public function getAuthorizeSucceeded(): ?string
    {
        return $this->authorizeSucceeded;
    }

    /**
     * Sets Authorize Succeeded.
     *
     * @maps AuthorizeSucceeded
     */
    public function setAuthorizeSucceeded(?string $authorizeSucceeded): void
    {
        $this->authorizeSucceeded = $authorizeSucceeded;
    }

    /**
     * Returns Succeeded.
     */
    public function getSucceeded(): ?string
    {
        return $this->succeeded;
    }

    /**
     * Sets Succeeded.
     *
     * @maps Succeeded
     */
    public function setSucceeded(?string $succeeded): void
    {
        $this->succeeded = $succeeded;
    }

    /**
     * Returns Authorize Failed.
     */
    public function getAuthorizeFailed(): ?string
    {
        return $this->authorizeFailed;
    }

    /**
     * Sets Authorize Failed.
     *
     * @maps AuthorizeFailed
     */
    public function setAuthorizeFailed(?string $authorizeFailed): void
    {
        $this->authorizeFailed = $authorizeFailed;
    }

    /**
     * Returns Failed.
     */
    public function getFailed(): ?string
    {
        return $this->failed;
    }

    /**
     * Sets Failed.
     *
     * @maps Failed
     */
    public function setFailed(?string $failed): void
    {
        $this->failed = $failed;
    }

    /**
     * Converts the RedirectionEndpointsModel object to a human-readable string representation.
     *
     * @return string The string representation of the RedirectionEndpointsModel object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'RedirectionEndpointsModel',
            [
                'authorizeSucceeded' => $this->authorizeSucceeded,
                'succeeded' => $this->succeeded,
                'authorizeFailed' => $this->authorizeFailed,
                'failed' => $this->failed
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->authorizeSucceeded)) {
            $json['AuthorizeSucceeded'] = $this->authorizeSucceeded;
        }
        if (isset($this->succeeded)) {
            $json['Succeeded']          = $this->succeeded;
        }
        if (isset($this->authorizeFailed)) {
            $json['AuthorizeFailed']    = $this->authorizeFailed;
        }
        if (isset($this->failed)) {
            $json['Failed']             = $this->failed;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
