<?php

declare(strict_types=1);

/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV3Lib\Models;

use SplititWebApiV3Lib\ApiHelper;
use stdClass;

class ShopperData implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $fullName;

    /**
     * @var string|null
     */
    private $email;

    /**
     * @var string|null
     */
    private $phoneNumber;

    /**
     * @var string|null
     */
    private $culture;

    /**
     * @var string|null
     */
    private $externalId;

    /**
     * Returns Full Name.
     */
    public function getFullName(): ?string
    {
        return $this->fullName;
    }

    /**
     * Sets Full Name.
     *
     * @maps FullName
     */
    public function setFullName(?string $fullName): void
    {
        $this->fullName = $fullName;
    }

    /**
     * Returns Email.
     */
    public function getEmail(): ?string
    {
        return $this->email;
    }

    /**
     * Sets Email.
     *
     * @maps Email
     */
    public function setEmail(?string $email): void
    {
        $this->email = $email;
    }

    /**
     * Returns Phone Number.
     */
    public function getPhoneNumber(): ?string
    {
        return $this->phoneNumber;
    }

    /**
     * Sets Phone Number.
     *
     * @maps PhoneNumber
     */
    public function setPhoneNumber(?string $phoneNumber): void
    {
        $this->phoneNumber = $phoneNumber;
    }

    /**
     * Returns Culture.
     */
    public function getCulture(): ?string
    {
        return $this->culture;
    }

    /**
     * Sets Culture.
     *
     * @maps Culture
     */
    public function setCulture(?string $culture): void
    {
        $this->culture = $culture;
    }

    /**
     * Returns External Id.
     */
    public function getExternalId(): ?string
    {
        return $this->externalId;
    }

    /**
     * Sets External Id.
     *
     * @maps ExternalId
     */
    public function setExternalId(?string $externalId): void
    {
        $this->externalId = $externalId;
    }

    /**
     * Converts the ShopperData object to a human-readable string representation.
     *
     * @return string The string representation of the ShopperData object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ShopperData',
            [
                'fullName' => $this->fullName,
                'email' => $this->email,
                'phoneNumber' => $this->phoneNumber,
                'culture' => $this->culture,
                'externalId' => $this->externalId
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->fullName)) {
            $json['FullName']    = $this->fullName;
        }
        if (isset($this->email)) {
            $json['Email']       = $this->email;
        }
        if (isset($this->phoneNumber)) {
            $json['PhoneNumber'] = $this->phoneNumber;
        }
        if (isset($this->culture)) {
            $json['Culture']     = $this->culture;
        }
        if (isset($this->externalId)) {
            $json['ExternalId']  = $this->externalId;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
