<?php

declare(strict_types=1);

/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV3Lib\Models;

use SplititWebApiV3Lib\ApiHelper;
use stdClass;

class UxSettingsModel implements \JsonSerializable
{
    /**
     * @var int[]|null
     */
    private $displayedInstallmentOptions;

    /**
     * Returns Displayed Installment Options.
     *
     * @return int[]|null
     */
    public function getDisplayedInstallmentOptions(): ?array
    {
        return $this->displayedInstallmentOptions;
    }

    /**
     * Sets Displayed Installment Options.
     *
     * @maps DisplayedInstallmentOptions
     *
     * @param int[]|null $displayedInstallmentOptions
     */
    public function setDisplayedInstallmentOptions(?array $displayedInstallmentOptions): void
    {
        $this->displayedInstallmentOptions = $displayedInstallmentOptions;
    }

    /**
     * Converts the UxSettingsModel object to a human-readable string representation.
     *
     * @return string The string representation of the UxSettingsModel object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'UxSettingsModel',
            ['displayedInstallmentOptions' => $this->displayedInstallmentOptions]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->displayedInstallmentOptions)) {
            $json['DisplayedInstallmentOptions'] = $this->displayedInstallmentOptions;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
