<?php

declare(strict_types=1);

/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV3Lib\Models;

use SplititWebApiV3Lib\ApiHelper;
use stdClass;

class VerifyAuthorizationResponse implements \JsonSerializable
{
    /**
     * @var bool
     */
    private $isAuthorized;

    /**
     * @var float|null
     */
    private $authorizationAmount;

    /**
     * @var AuthorizationModel|null
     */
    private $authorization;

    /**
     * @param bool $isAuthorized
     */
    public function __construct(bool $isAuthorized)
    {
        $this->isAuthorized = $isAuthorized;
    }

    /**
     * Returns Is Authorized.
     */
    public function getIsAuthorized(): bool
    {
        return $this->isAuthorized;
    }

    /**
     * Sets Is Authorized.
     *
     * @required
     * @maps IsAuthorized
     */
    public function setIsAuthorized(bool $isAuthorized): void
    {
        $this->isAuthorized = $isAuthorized;
    }

    /**
     * Returns Authorization Amount.
     */
    public function getAuthorizationAmount(): ?float
    {
        return $this->authorizationAmount;
    }

    /**
     * Sets Authorization Amount.
     *
     * @maps AuthorizationAmount
     */
    public function setAuthorizationAmount(?float $authorizationAmount): void
    {
        $this->authorizationAmount = $authorizationAmount;
    }

    /**
     * Returns Authorization.
     */
    public function getAuthorization(): ?AuthorizationModel
    {
        return $this->authorization;
    }

    /**
     * Sets Authorization.
     *
     * @maps Authorization
     */
    public function setAuthorization(?AuthorizationModel $authorization): void
    {
        $this->authorization = $authorization;
    }

    /**
     * Converts the VerifyAuthorizationResponse object to a human-readable string representation.
     *
     * @return string The string representation of the VerifyAuthorizationResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'VerifyAuthorizationResponse',
            [
                'isAuthorized' => $this->isAuthorized,
                'authorizationAmount' => $this->authorizationAmount,
                'authorization' => $this->authorization
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['IsAuthorized']            = $this->isAuthorized;
        if (isset($this->authorizationAmount)) {
            $json['AuthorizationAmount'] = $this->authorizationAmount;
        }
        if (isset($this->authorization)) {
            $json['Authorization']       = $this->authorization;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
