<?php

declare(strict_types=1);

/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV3Lib;

use CoreInterfaces\Http\HttpConfigurations;
use SplititWebApiV3Lib\Authentication\OAuth2ProductionCredentials;
use SplititWebApiV3Lib\Authentication\OAuth2ProductionCredentialsBuilder;
use SplititWebApiV3Lib\Authentication\OAuth2SandboxCredentials;
use SplititWebApiV3Lib\Authentication\OAuth2SandboxCredentialsBuilder;
use SplititWebApiV3Lib\Proxy\ProxyConfigurationBuilder;

/**
 * An interface for all configuration parameters required by the SDK.
 */
interface ConfigurationInterface extends HttpConfigurations
{
    /**
     * Get current API environment
     */
    public function getEnvironment(): string;

    /**
     * Get the credentials to use with OAuth2Sandbox
     */
    public function getOAuth2SandboxCredentials(): OAuth2SandboxCredentials;

    /**
     * Get the credentials builder instance to update credentials for OAuth2Sandbox
     */
    public function getOAuth2SandboxCredentialsBuilder(): ?OAuth2SandboxCredentialsBuilder;

    /**
     * Get the credentials to use with OAuth2Production
     */
    public function getOAuth2ProductionCredentials(): OAuth2ProductionCredentials;

    /**
     * Get the credentials builder instance to update credentials for OAuth2Production
     */
    public function getOAuth2ProductionCredentialsBuilder(): ?OAuth2ProductionCredentialsBuilder;

    /**
     * Represents the proxy configurations for API calls.
     */
    public function getProxyConfigurationBuilder(): ProxyConfigurationBuilder;

    /**
     * Get the base uri for a given server in the current environment.
     *
     * @param string $server Server name
     *
     * @return string Base URI
     */
    public function getBaseUri(string $server = Server::DEFAULT_): string;
}
