<?php

declare(strict_types=1);

/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV3Lib;

/**
 * Baseurl aliases
 */
class Server
{
    public const DEFAULT_ = 'default';

    public const ACCESS_TOKEN_SERVER = 'access token server';

    public const ACCESS_TOKEN_SERVER1 = 'access token server1';
}
